### ISSUE TITLE
Companion disconnects from OBS instance

### ISSUE THREAD

**Issue by magnusoverli** [bitfocus/companion-module-obs-studio#10]
When using the "Reconnect to OSB" service, companion disconnects from the current OBS instance and does not reconnect. After clicking a button with the "Reconnect..." service on it, OBS has the status "ERROR" in the Connections / Instances overview.

As far as I can see nothing is showing up in the logs. It looks like it only implements the disconnection and not the reconnection part of the service.
After restarting Companion everything is working again.

Build: 2.0.0 (2.0.0-9e7311c-2009)
OBS/Companion locally installed on a Win10 server.

**Comment by magnusoverli** [comment]
The issue can be worked around by disabling and the enabling the OBS instance.

**Comment by JeffreyDavidsz** [comment]
@magnusoverli there was a big update which was not into core yet. I've just upgraded that module, so try it in about 15min

**Comment by magnusoverli** [comment]
I just tried again, now on version 2.0.0-26851f7-2021. I am now unable to get a stable connection to OBS at all. Still the debug log shows:
`24. 09:14:15 instance(OBS MAIN): Success! Connected.
24. 09:14:15 instance(DJjDf_mmp): instance configuration updated`
But the instance status flickers between `CONNECTING` and `ERROR`.

**Comment by bryce-seifert** [comment]
Fixed with https://github.com/bitfocus/companion-module-obs-studio/pull/11
