### ISSUE TITLE
[Question] OBS Websocket 5.0

### ISSUE THREAD

**Issue by gohamstergo** [bitfocus/companion-module-obs-studio#101]
@bryce-seifert Just wondering if you've heard about the 5.0 rewrite and if you plan to support. Thanks for the continued work, as always.
https://github.com/Palakis/obs-websocket/releases/tag/4.9.1 (lower on that page)

**Comment by bryce-seifert** [comment]
Good question! This module uses obs-websocket-js, and they've announced [they're working on version 5 support](https://github.com/obs-websocket-community-projects/obs-websocket-js/discussions/241), so we should be set!

**Comment by gohamstergo** [comment]
great, thank you!
