### ISSUE TITLE
Change position sources with SetSceneItemProperties

### ISSUE THREAD

**Issue by Cypris2010** [bitfocus/companion-module-obs-studio#105]
It wolud be great if you could manipulate the properties of sceneitem / sources over the SetSceneItemProperties https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#setsceneitemproperties

I think scale and position would be a great start.

And thank you for the great work you are doing.

**Comment by bryce-seifert** [comment]
@Cypris2010 Thanks, I have this lined up for the next release!
https://github.com/bryce-seifert/companion-module-obs-studio/commit/9e5d097351d57c3beff77e7f740f17604a426546
