### ISSUE TITLE
Open fullscreen

### ISSUE THREAD

**Issue by Tanis74** [bitfocus/companion-module-obs-studio#106]
It would be great if you could open or close fullscreen over the companion.
https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#openprojector

And thank you))

**Comment by bryce-seifert** [comment]
@Tanis74 I got this done, and will include it with the next release.
https://github.com/bitfocus/companion-module-obs-studio/commit/7da38301f2415ca1eae983f3b872701063dcd26c
