### ISSUE TITLE
Add source media filename variable

### ISSUE THREAD

**Issue by nacalai** [bitfocus/companion-module-obs-studio#108]
Currently we have variables like media status and recording filename available in Companion. In our TV production we would love to have a media filename variable as well. As in, showing the filename of a media source (and preferrably without the .mp4 extension). Should be easy to implement, I just don't have the skills to do it sadly.

**Comment by nacalai** [comment]
Aha. I was thinking about it changing the source name and just use that,
but it needs to know the source filename to do that so I don't really see
how I could make it work. Any suggestions?

**Comment by bryce-seifert** [comment]
It seems like this is likely not possible with the current API. If you'd like to see it, I'd suggest opening a request in the [OBS Websocket repo](https://github.com/Palakis/obs-websocket/issues?q=is%3Aissue+media+path+is%3Aopen).

**Comment by nacalai** [comment]
Hi there. I opened a request at websocket repo. They claim it is already there?

> https://github.com/Palakis/obs-websocket/issues/805#issuecomment-899083815

**Comment by nacalai** [comment]
I guess this makes more sense now. Is it possible implementing this then? :) 

> There is no event afaik that includes the info natively. GetSourceSettings is not an event but a request(that you have to poll). Simplest solution for that is to listen for the MediaStarted event and then fire the GetSourceSettings request against that source.
So to rephrase your feature request: You want the filename to be included in the Media* events.

**Comment by bryce-seifert** [comment]
Ok I think I found a workaround using the GetSourceSettings item that was pointed out above. It will be included on the next beta version.

**Comment by nacalai** [comment]
> Ok I think I found a workaround using the GetSourceSettings item that was pointed out above. It will be included on the next beta version.

Wow thanks! That was fast. Looking forward to try it when the next build comes out. Happens every few days or so?

**Comment by bryce-seifert** [comment]
@nacalai This should be in the latest beta for you to try!
