### ISSUE TITLE
Variables for Source and Input volume levels

### ISSUE THREAD

**Issue by eric** [bitfocus/companion-module-obs-studio#110]
There are actions to adjust the volume level for sources, but currently not a way to see what the current volume level is.

It would be helpful to be able to get feedback on what the current level is.

**Comment by bryce-seifert** [comment]
I have this ready to go with both variable and feedback for the next release https://github.com/bryce-seifert/companion-module-obs-studio/commit/2dfa29d26efad93eb9dad839601c6f3e44cb8a72

**Comment by eric** [comment]
This is great!

**Comment by nacalai** [comment]
Any news on when this will be put in? Really looking forward to it!

**Comment by bryce-seifert** [comment]
Should be soon, just created a pull request https://github.com/bitfocus/companion-module-obs-studio/pull/115
