### ISSUE TITLE
Media filename variable not updating

### ISSUE THREAD

**Issue by nacalai** [bitfocus/companion-module-obs-studio#112]
Hi there. Loving the added media filename variable, however I discovered that the variable doesn't update if I go into a media source and pick another video as the file.

It does update if:
- I output it to program.
- I restart companion, without putting the media source into program. This indicates it's not limitation in OBS where I thought you would have to make the media active for it to update.

**Comment by bryce-seifert** [comment]
Currently this is expected behaviors, it's only looking for changed when a media clip is played.

I'll see if I can find a way to check this more regularly, while also not overloading it by checking too often.
