### ISSUE TITLE
Connection flapping to OBS websocket server

### ISSUE THREAD

**Issue by andycapx** [bitfocus/companion-module-obs-studio#113]
I am running OBS Studio and Websocket Server on Debian 11. Currently both applications are compiled from latest source, OBS Studio 27.1.0-rc1-1-gb34e6ae76 (linux) and Bitfocus Companion 2.2.0 (2.2.0-93832640-3524). Set both to port 4444 (using local IP or 127.0.0.1). Popup "New WebSocket connection - Client 127.0.0.1:56xxx connected"  and "WebSocket Client disconnected - Client unknown disconnected" and "Houston we have a problem ..." within OBS Studio. This is changing/repeating within interval of 5 seconds. After deleting OBS-Studio module, no more of this error messages are viewed. Turning on again, same behavior. 
![obs](https://user-images.githubusercontent.com/89852833/131522144-479a23eb-cc21-43e0-a45c-9a3c04442f34.jpg)

**Comment by bryce-seifert** [comment]
What version of obs-websocket are you using?

**Comment by andycapx** [comment]
Hi, I am using 1.0.24

**Comment by bryce-seifert** [comment]
Are you able to see an errors in the Log tab on Companion?

**Comment by andycapx** [comment]
Please find attached the logs. I cannot see some more history. I guess the logs are cleaned each time the application is started.

[logs.zip](https://github.com/bitfocus/companion-module-obs-studio/files/7098572/logs.zip)

**Comment by bryce-seifert** [comment]
@andycapx Thanks. Did you mean to close this issue? Or are you still having the problem?

**Comment by andycapx** [comment]
In general the logs looks fine, but the  problem is still there. Even with no detailed log entry causing the connection loss.

**Comment by bryce-seifert** [comment]
Would you be able to put websocket in debug mode, and upload those logs from OBS?

**Comment by andycapx** [comment]
I have reinstalled everything and the problem has gone. So please close this ticket.
Thank you very much for your effort and investigation.
