### ISSUE TITLE
Variables stop updating

### ISSUE THREAD

**Issue by nacalai** [bitfocus/companion-module-obs-studio#114]
Hi there! This is a bit of a strange one. All OBS variables just seemingly stop updating after a certain time, or, after certain actions. I am having troubles troubleshooting this and narrowing it down.

Running latest beta. It also happened many many betas back.

I have traditional mixer setup in Companion. Cam 1-4, with green/red color feedbacks. I can spam those as much as I want without any problems. As soon as I start playing back videos etc, the variables just stop updating and I have to restart companion to make them work again, which messes up everything since we rely on these feedbacks to run our shows.

There are (seemingly) no websocket interruptions. Actions work just fine. It's only the variables that stop working.

Unfortunately I don't have much more info to give, but please let me know if you need anything more from me.

Setup: W10 64, Latest OBS, Latest Companion beta.

**Comment by eric** [comment]
Sounds like it may be related to what I saw in #111

**Comment by nacalai** [comment]
@eric Perhaps. Although in this case the variables/feedback stop working almost instantly, regardless of how long OBS is running etc. It happens as soon as I start switching to video playbacks and stuff. Very strange.

**Comment by bryce-seifert** [comment]
For testing purposes: which variables are you using that stop working?

**Comment by nacalai** [comment]
Well, it's all of them. That is the odd part. They all stop updating. I am
mainly pulling preview/active scene

**Comment by bryce-seifert** [comment]
I think I figured out why this is linked to videos playing. Turns out, for some reason when manually playing a clip, OBS websocket is firing both MediaPlayed and MediaStarted event, and in between those the module was trying to update the list of media sources which caused it to be undefined during the second check. So I have a fix that I'm going to test that should resolve.

**Comment by nacalai** [comment]
That sounds great! But isn't it weird that all variables just stopped
updating because of that

**Comment by bryce-seifert** [comment]
It was causing an uncaught exception, so that is expected that it affected everything

**Comment by nacalai** [comment]
Ah I see. We run the next show in 10 hours and we are a bit dependent on
the feedbacks. Too much to hope for a new companion build by then?

**Comment by bryce-seifert** [comment]
Have you tried [this build](https://bitfocus.io/companion/download/build/companion-2.2.0-c1789b53-3510-win64.exe)? It's right before the change that I think caused this issue was made.

**Comment by bryce-seifert** [comment]
@nacalai Should be in the betas now, let me know if this fixes it.

**Comment by XDelta778** [comment]
Hello ! The media file name still does not update on companion v3.2.2. Only the filename of one video source is rarely updated, and 3 other sources never finds the name of the mp4 file

**Comment by bryce-seifert** [comment]
@XDelta778 Can you try the latest companion beta? There were additional fixes to this recently for certain files.

And just to make sure; are these Media Source types? And what version of OBS?

**Comment by XDelta778** [comment]
@bryce-seifert Thank you for your answer, I installed the beta 3.3.0 and now it is working well ! 

OBS version 29.1.3 and all are effectively Media Sources
