### ISSUE TITLE
DSK plug-in

### ISSUE THREAD

**Issue by stevespaw** [bitfocus/companion-module-obs-studio#117]
I have just started looking at OBS again. I like using the DSK plug-in.
[https://obsproject.com/forum/resources/downstream-keyer.1254/](url)
Is there a way to control with the module?
This would be super powerful...

Steve

**Comment by bryce-seifert** [comment]
It doesn't seem like the DSK plug-in has an API or way to control it using websocket. So unfortunately until they have that, it won't fit in with this module.
