### ISSUE TITLE
OBS  instance

### ISSUE THREAD

**Issue by wolfling366** [bitfocus/companion-module-obs-studio#125]
I've just installed Companion v2.1.3 on my PC. When I try to add a local instance of OBS Studio, I get a seeries of errors in the log. And when I say "a series of errors";
That's 110 "Connection lost to OBS" per second.

[Streamdeck + OBSStudio + BitFocus Companion.txt](https://github.com/bitfocus/companion-module-obs-studio/files/7504819/Streamdeck.%2B.OBSStudio.%2B.BitFocus.Companion.txt)

Meanwhile, in the instances tab, it blinks between OK and ERROR so fast that the colours blend together. (If it doesn't trigger an epileptic fit.)

This eventually crashes the companion until it stops detecting the Stream Deck, and then the GUI starts havaing connection issues to the Companion.

Because I run a dual rig, I tried connecting to the second PC's instance; it did the whole thing to that OBS too, just not fast enough to crash the Companion. What it does do is start chewing up 10k of bandwidth that grows steadily. 60 seconds later it was using 50kbps.

Any ideas?

**Comment by bryce-seifert** [comment]
This should be resolved by [downloading the one of the latest 2.2.0 betas](https://bitfocus.io/companion/download/builds/)

**Comment by xzxer** [comment]
I am running the latest version of the beta build and i am also having this same issue with OBS.

**Comment by bryce-seifert** [comment]
Any other details? OS? Using a password? What version of websocket?

**Comment by bryce-seifert** [comment]
@wolfling366 Can you verify your version of obs websocket? 
Seems like if you're using 5, it could cause a similar issue (see [here](https://github.com/bitfocus/companion-module-obs-studio/issues/126))

**Comment by bryce-seifert** [comment]
This is likely an issue of the wrong websocket version. I have added a warning about using versions >= 5 in the latest beta.
