### ISSUE TITLE
OBS wont connect to Companion

### ISSUE THREAD

**Issue by xzxer** [bitfocus/companion-module-obs-studio#126]
I am running the latest version of companion 2.2.0 (2.2.0-f82fb99c-3614) and am having some issues with connecting OBS.

I cannot get it to connect to companion. Sample of the log file:

21.11.17 11:19:45 instance(obs): Connection lost to OBS.
21.11.17 11:19:45 instance(obs): Connection lost to OBS.
21.11.17 11:19:45 instance(obs): Connection lost to OBS.
21.11.17 11:19:45 instance(obs): Connection lost to OBS.
21.11.17 11:19:45 instance(obs): Connection lost to OBS.
21.11.17 11:19:45 instance(obs): Connection lost to OBS.
21.11.17 11:19:45 instance(obs): Connection lost to OBS.
21.11.17 11:19:45 instance(obs): Connection lost to OBS.
21.11.17 11:19:45 instance(obs): Connection lost to OBS.
21.11.17 11:19:45 instance(obs): Connection lost to OBS.
21.11.17 11:19:45 instance(obs): Connection lost to OBS.
21.11.17 11:19:45 instance(obs): Connection lost to OBS.
21.11.17 11:19:45 instance(obs): Connection lost to OBS.

**Comment by bryce-seifert** [comment]
What OS, what version of OBS websocket?

**Comment by xzxer** [comment]
I was running 5.0.0 alpha 2

Just switched to 4.9.1 and it seems to have corrected the issue.

**Comment by bryce-seifert** [comment]
Yeah this has not been tested with 5.0, which is a major overhaul of OBS websocket. The library we use, obs-websocket-js, doesn't support 5.0 yet, but will.

**Comment by xzxer** [comment]
> Yeah this has not been tested with 5.0, which is a major overhaul of OBS websocket. The library we use, obs-websocket-js, doesn't support 5.0 yet, but will.

Thanks for the info. I will be on the look out for 5.0 support
