### ISSUE TITLE
Open properties dialoge in OBS

### ISSUE THREAD

**Issue by Cypris2010** [bitfocus/companion-module-obs-studio#128]
Perhaps I have the wrong angle on this topic, so please feel free to tell me your opinion.

I think it would be great to have a button on the streamdeck that could open the property window of OBS for a specific scene item.

I have ten mediasources in one scene an I want to change die connected video during production. I don't want to go to the scene and change it with the mouse. Well I down't want to go there with the mouse, I still have to use it when the window is open.

I could not find a API function for opening the properties. Perhaps there is none an the idea is finished. But I think it would be cool ihr it would be possible with companion if possible.

**Comment by Cypris2010** [comment]
I found the item in die OBS API, seems to be missing in the Websocket. It's one of the last entries on this doc page:
https://obsproject.com/docs/reference-frontend-api.html

**Comment by bryce-seifert** [comment]
Nice! If you want to submit it as a [request to add to websocket](https://github.com/obsproject/obs-websocket/issues), and it gets added, we'd be able to add it here!

Also not sure if this works with your workflow, but I should be able to make a button that replaces the file path? Not sure if that's another way to approach this that makes sense.

**Comment by bryce-seifert** [comment]
Went ahead and requested this in OBS Websocket repo https://github.com/obsproject/obs-websocket/issues/864

**Comment by Cypris2010** [comment]
Had not found the time, yet. So thank you for it :)

**Comment by bryce-seifert** [comment]
@Cypris2010 This feature is now available in the [beta builds of Companion](https://bitfocus.io/companion/download/builds/). Note it requires obs-websockets 5.0
