### ISSUE TITLE
Add "OBS: Change color when source muted" to feedback actions

### ISSUE THREAD

**Issue by jefuslives** [bitfocus/companion-module-obs-studio#129]
**Describe the feature**
The ability to use a source's mute state as a feedback param, just like is currently available for source visibility. (See feedback action 'obs: Change colors when source visible')

**Usecases**
Mute buttons that change color, etc. depending on the associated source's mute state.

**Comment by bryce-seifert** [comment]
@jefuslives This is available in the Companion 2.2.0 betas, which you can download [here](https://bitfocus.io/companion/download/builds/), as the "Audio Muted" feedback
