### ISSUE TITLE
Feature request: Change the text of a Text(GDI+) source

### ISSUE THREAD

**Issue by 22hn** [bitfocus/companion-module-obs-studio#13]
Would like to have an action in companion for changing the text of a OBS Text(GDI+) source.

Have a scene for speaker nametag that is linked in as a source in my live video scenes and I'm controlling the visibility of that source from a stream deck button.

So what I would like to do is to have a button called "select nametag" that switches to another page on the stream deck, presenting me with choices of different speaker names. When I select a name, that would redefine the button text of my nametag on/off button on the main page (the one controlling the OBS source) and also set the text property of the OBS source. So when I then activate the nametag, the selected name would show in the feed.

Assume this is doable with SetTextGDIPlusProperties in obs-websocket.

**Comment by cjdenio** [comment]
This looks doable! The only hitch would be the button whose text changes with the speaker name.

My best recommendation would be to write a script that changes the button name over OSC. Companion *does* support variables, but I think this may be too specific to add.

Anyway, I'll put up a PR to add the SetTextProperties action!

**Comment by 22hn** [comment]
Ah, you're right... Thought I've seen an action for changing a button's text, but that was for changing it's color only.

But if the rest is doable I'm very thankful…!

**Comment by 22hn** [comment]
Caleb, would you also take a look at #12? Similar issue, quick fix... :-)

**Comment by cjdenio** [comment]
I've actually started writing a fix for that :smile: I should be able to submit it later today.

**Comment by 22hn** [comment]
Great!

And then what, do they have to release a new build of companion to make the fix available? (I'm new to the github workflow...)

**Comment by cjdenio** [comment]
I'm not 100% sure; I think once the PR gets merged it'll automatically get built and become available here: https://bitfocus.io/companion/download/builds

**Comment by DachsbauTV** [comment]
Is there an easy way to have a reverse version of this implemented? basically a feedback module that can read the text out of a Text source, so you can preview a text in a lower third before you put it on air. This would be especially useful if your text source gets its data from an external source (e.g. live scoring in a sporting event)

**Comment by DachsbauTV** [comment]
By now i finally understand what I actually need: 

Just a Variable that reads the text from the Text(GDI+) Source.

Anyone an idea if this could work?
