### ISSUE TITLE
Using variables in "obs: Set Source Properties"

### ISSUE THREAD

**Issue by Cypris2010** [bitfocus/companion-module-obs-studio#131]
Can you change the input fields für the properties so that variables could be used in it?

Don't know if this would be practical in the general usecase, but I have similar buttons on many pages that I have to change if I want to change the general position of my scene items.

**Comment by bryce-seifert** [comment]
@Cypris2010 This is in the [latest beta build](https://bitfocus.io/companion/download/builds/). Let me know if you run into any issues!
