### ISSUE TITLE
OBS Support - Grouped Sources

### ISSUE THREAD

**Issue by Mushiiies** [bitfocus/companion-module-obs-studio#132]
Companion is unable to recognise whether a source is enabled in a scene, or even if it is visible, if the source is within a group.

**Comment by bryce-seifert** [comment]
@Mushiiies Grouped sources are supposed in the Companion 2.2.0 betas, which you can download [here](https://bitfocus.io/companion/download/builds/).

**Comment by Mushiiies** [comment]
Ah thank you, I am running live show so I didn't look at the beta. Guess that message is more of a disclaimer than a huge warning haha
