### ISSUE TITLE
"Toggle visibility scene item" not toggling properly

### ISSUE THREAD

**Issue by bendoll** [bitfocus/companion-module-obs-studio#133]
When setting up a button to toggle visibility of a source, the button toggles the visibility once and then will not toggle again until the scene is changed. This button is expected to toggle on or off the source every time it's pressed. As a broadcast director whose responsibilities include graphics operation, I use scenes that contain multiple sources that are shown one at a time. I'd like to rely on this feature to quickly check that my graphics work as intended before taking them live.

I'm using OBS with obs-websockets on Windows 10 and a base model Elgato Stream Deck. Please reply with any additional info or examples I should provide and I'll be happy to help.

**Comment by bryce-seifert** [comment]
@bendollare Are you using the latest Companion 2.2.0 beta, which you can download [here](https://bitfocus.io/companion/download/builds/).

**Comment by bendoll** [comment]
I apologize, using the latest beta build fixes it. Thanks for pointing me in the right direction.
