### ISSUE TITLE
OBS still crashes on exit when using Websocket 4.9.1 and Companion 2.2.x

### ISSUE THREAD

**Issue by BigJinge** [bitfocus/companion-module-obs-studio#134]
Hi,

Whilst having to use a build of Companion 2.2 beta for a bug fix, the latest version of OBS crashes on exit when using Websocket 4.9.1

You either get a "OBS has crashed" message or an exe crash message.
![OBS_Crash_1](https://user-images.githubusercontent.com/19828427/147399117-013e43ff-fe15-4d2c-bba0-72c37254ac8e.PNG)
![OBS_Crash_2](https://user-images.githubusercontent.com/19828427/147399118-f7e79982-76bd-4db7-9e26-b4da07bebf98.PNG)

According to previously closed ticket [52,](https://github.com/bitfocus/companion-module-obs-studio/issues/52) 4.9.1 fixed an issue with 2.2 that stopped this from happening. 

It's still happening.

OBS crash txt file attached.
[Crash 2021-12-13 15-27-36.txt](https://github.com/bitfocus/companion-module-obs-studio/files/7776584/Crash.2021-12-13.15-27-36.txt)

Windows 10 x64 21H1
Websocket 4.9.1
OBS 27.1.3
Companion build 2.2.0-5e326f35-3639

 TIA

**Comment by bryce-seifert** [comment]
I think this is an issue on the obs-websocket side. They're currently working on a rewrite with 5.0, so I think our best bet might be waiting for that as I don't think they're working on 4.x anymore. I'll keep an eye on it.

**Comment by BigJinge** [comment]
Everything was working before I changed from Companion 2.1.3 over to 2.2.x . The question being is, given what the dump file says, is the issue with 2.2 only, an incompatibility of both 2.2 and 4.9.1 or only with 4.9.1 ?

**Comment by bryce-seifert** [comment]
I'm not entirely sure, and I'm not sure I have the expertise to gleam that from the crash file. We could raise this is an issue with the obs-websocket folks and see if they have more insight.

**Comment by bryce-seifert** [comment]
So it seems like this is something that will be able to be fixed once 5.0.0 is out

> This crash is due to Companion running polling operations while the scene collection is changing. This issue can be mitigated on clients using obs-websocket 5.0.0 by pausing polling between the SceneCollectionChanging and SceneCollectionChanged events.

And the reason it's happening in 2.2.0 and not 2.1.3 is there is a lot more polling going on to accommodate new features.

**Comment by BigJinge** [comment]
For reference, if someone else has this issue.

It's a shame that the OBS module obs: Set Source Visibility, bugged in 2.1.3 (and fixed 2.2.x) requires an alpha version of WebSocket 5.0.0 to work with the 2.2.x beta that fixes it. 

However, with the latest third Websocket 5.0.0 alpha installed, it doesn't fix the issue. The OBS module flips back and forth between OK and Error many times a second. These constant tries efffectively hang Companion.

Given the toggle needed, I had to remove websocket and the OBS module using Vicreo instead.

**Comment by bryce-seifert** [comment]
> However, with the latest third Websocket 5.0.0 alpha installed, it doesn't fix the issue. The OBS module flips back and forth between OK and Error many times a second.
This is because obs-websocket 5.0.0 is a complete rewrite , therefore not currently compatible with this module at all until it's rewritten.

Sorry if my guidance was misconstrued– I was suggesting the solution will come once we transition the module to the new version of obs-websocket, not by upgrading the websocket client on the user end.

**Comment by bryce-seifert** [comment]
@BigJinge Curious if you have tried the latest [OBS 27.2 beta](https://github.com/obsproject/obs-studio/releases/tag/27.2.0-beta4)? It might be dumb luck, but I haven't seen a Scene Collection change crash yet (I'm on Mac, though).

**Comment by bryce-seifert** [comment]
Going to close this, as someone else also reported OBS 27.2 seems to fix this https://github.com/obsproject/obs-websocket/issues/839#issuecomment-1040698469
