### ISSUE TITLE
Late update of media variables

### ISSUE THREAD

**Issue by CoastIT** [bitfocus/companion-module-obs-studio#147]
In 1.0.31 some of the media variables are updated late.
E.g. "Media status for <Source>"

Use case:
- Fully automated switching in OBS with automated scene switcher -> no button clicks during the procedure
- "Media status for Source-01" is Playing
- OBS switches to another scene wich plays another source
-> Current OBS media status is not reflected in "Media status for Source-01" (cheked via companion GUI) , it stays at "Playing" and is updated only after another transition.

I wonder if somebody else is able to reproduce it.

**Comment by bryce-seifert** [comment]
I did some trial/error and wasn't able to recreate but I'm not sure I have the same set-up.

Are your media clips set to "Restart playback when source becomes active"? I found that if that's not check the media does continue playing, even if it's no in the active scene.

If not, perhaps a screen share would be helpful to see your set-up?

**Comment by CoastIT** [comment]
I did a couple of tests with v1.0.31 of the module and realized that the problem does not occure all the time but quite often.
Looks like that the obs module is randomly missing some of the event notifications from obs.

I did a couple of manual transitions in obs.

**This is from the obs logfile (tail -f ... | grep MediaEnded):**
20:30:07.088: [obs-websocket] Update << '{"sourceKind":"ffmpeg_source","sourceName":"<Media_Source_03>","update-type":"MediaEnded"}'
20:30:13.332: [obs-websocket] Update << '{"sourceKind":"ffmpeg_source","sourceName":"<Media_Source_04>","update-type":"MediaEnded"}'
20:30:21.694: [obs-websocket] Update << '{"sourceKind":"ffmpeg_source","sourceName":"<Media_Source_05>","update-type":"MediaEnded"}'
20:30:31.034: [obs-websocket] Update << '{"sourceKind":"ffmpeg_source","sourceName":"<Media_Source_06>","update-type":"MediaEnded"}'
20:30:35.096: [obs-websocket] Update << '{"sourceKind":"ffmpeg_source","sourceName":"<Media_Source_07>","update-type":"MediaEnded"}'
20:30:41.819: [obs-websocket] Update << '{"sourceKind":"ffmpeg_source","sourceName":"<Media_Source_08>","update-type":"MediaEnded"}'
20:30:50.074: [obs-websocket] Update << '{"sourceKind":"ffmpeg_source","sourceName":"<Media_Source_09>","update-type":"MediaEnded"}'
20:30:57.794: [obs-websocket] Update << '{"sourceKind":"ffmpeg_source","sourceName":"<Media_Source_01>","update-type":"MediaEnded"}'
20:31:00.204: [obs-websocket] Update << '{"sourceKind":"ffmpeg_source","sourceName":"<Media_Source_02>","update-type":"MediaEnded"}'
20:31:03.318: [obs-websocket] Update << '{"sourceKind":"ffmpeg_source","sourceName":"<Media_Source_03>","update-type":"MediaEnded"}'
20:31:06.399: [obs-websocket] Update << '{"sourceKind":"ffmpeg_source","sourceName":"<Media_Source_04>","update-type":"MediaEnded"}'
20:31:11.181: [obs-websocket] Update << '{"sourceKind":"ffmpeg_source","sourceName":"<Media_Source_05>","update-type":"MediaEnded"}'
20:31:13.298: [obs-websocket] Update << '{"sourceKind":"ffmpeg_source","sourceName":"<Media_Source_06>","update-type":"MediaEnded"}'
20:31:17.106: [obs-websocket] Update << '{"sourceKind":"ffmpeg_source","sourceName":"<Media_Source_07>","update-type":"MediaEnded"}'
20:31:24.195: [obs-websocket] Update << '{"sourceKind":"ffmpeg_source","sourceName":"<Media_Source_08>","update-type":"MediaEnded"}'
20:31:29.659: [obs-websocket] Update << '{"sourceKind":"ffmpeg_source","sourceName":"<Media_Source_09>","update-type":"MediaEnded"}'
20:31:40.818: [obs-websocket] Update << '{"sourceKind":"ffmpeg_source","sourceName":"<Media_Source_01>","update-type":"MediaEnded"}'
20:31:43.067: [obs-websocket] Update << '{"sourceKind":"ffmpeg_source","sourceName":"<Media_Source_02>","update-type":"MediaEnded"}'
20:31:44.801: [obs-websocket] Update << '{"sourceKind":"ffmpeg_source","sourceName":"<Media_Source_03>","update-type":"MediaEnded"}'
20:31:47.132: [obs-websocket] Update << '{"sourceKind":"ffmpeg_source","sourceName":"<Media_Source_04>","update-type":"MediaEnded"}'
20:32:17.463: [obs-websocket] Update << '{"sourceKind":"ffmpeg_source","sourceName":"<Media_Source_05>","update-type":"MediaEnded"}'
20:32:47.818: [obs-websocket] Update << '{"sourceKind":"ffmpeg_source","sourceName":"<Media_Source_06>","update-type":"MediaEnded"}'
20:33:18.131: [obs-websocket] Update << '{"sourceKind":"ffmpeg_source","sourceName":"<Media_Source_07>","update-type":"MediaEnded"}'

**This is, from the same period, from the companion obs module (I've added a debug logging in "self.obs.on('MediaEnded', (data) => {)"):**
MEDIA ENDED FOR SOURCE <Media_Source_03>
MEDIA ENDED FOR SOURCE <Media_Source_07>
MEDIA ENDED FOR SOURCE <Media_Source_08>
MEDIA ENDED FOR SOURCE <Media_Source_09>
MEDIA ENDED FOR SOURCE <Media_Source_03>
MEDIA ENDED FOR SOURCE <Media_Source_04>
MEDIA ENDED FOR SOURCE <Media_Source_05>
MEDIA ENDED FOR SOURCE <Media_Source_07>
MEDIA ENDED FOR SOURCE <Media_Source_08>
MEDIA ENDED FOR SOURCE <Media_Source_09>
MEDIA ENDED FOR SOURCE <Media_Source_03>
MEDIA ENDED FOR SOURCE <Media_Source_07>

I'm running companion and obs on the same host with obs websocket 4.9.1.
The problem can be reproduced on another computer.

Other things which rely on events seems to work fine, for example I have not seen any problem with the "Transition in Progress" feedback (TransitionBegin/TransitionEnd events).
Also toggling between play/stop/pause of a single scene in obs seems to work fine.

Do you know how I can enable debug logging in the obs-websocket-js module?

**Comment by bryce-seifert** [comment]
Here's some info on debugging with [websocket-js](https://github.com/obs-websocket-community-projects/obs-websocket-js#debugging).

I'm wondering if this will still be persistent with 5.0.0

**Comment by CoastIT** [comment]
Thank you very much for the hint. I've already tried it with the set DEBUG but it was not working. But I was not aware of the DEVELOPER flag. 
However, just in case somebody reads this and wants to enable debug of the obs-websocket-js. The following works for me on windows:
`set DEVELOPER=true`
`set DEBUG=obs-websocket-js:*`
`yarn headless > "output_file" 2>&1`

I think the problem is somewhere between the obs-websocket-js and the obs module. Looks like the event is emitted but not recieved by the obs module.
I'll stop here and check again when the latest obs-websocket-js has been integrated.

***** GOOD CASE
`2022-02-25T20:26:42.394Z obs-websocket-js:Socket [OnMessage]: MessageEvent { target: <ref *1> WebSocket { _events: [Object: null prototype] { error: [Function], open: [Function], close: [Function], message: [Function] }, _eventsCount: 4, _maxListeners: undefined, _binaryType: 'nodebuffer', _closeCode: 1006, _closeFrameReceived: false, _closeFrameSent: false, _closeMessage: '', _closeTimer: null, _extensions: {}, _protocol: '', _readyState: 1, _receiver: Receiver { _writableState: [WritableState], _events: [Object: null prototype], _eventsCount: 6, _maxListeners: undefined, _binaryType: 'nodebuffer', _extensions: {}, _isServer: false, _maxPayload: 104857600, _bufferedBytes: 18594, _buffers: [Array], _compressed: false, _payloadLength: 90, _mask: undefined, _fragmented: 0, _masked: false, _fin: true, _opcode: 1, _totalPayloadLength: 0, _messageLength: 0, _fragments: [], _state: 4, _loop: true, [Symbol(kCapture)]: false, [Symbol(websocket)]: [Circular *1] }, _sender: Sender { _extensions: {}, _socket: [Socket], _firstFragment: true, _compress: false, _bufferedBytes: 0, _deflating: false, _queue: [] }, _socket: Socket { connecting: false, _hadError: false, _parent: null, _host: null, _readableState: [ReadableState], _events: [Object: null prototype], _eventsCount: 4, _maxListeners: undefined, _writableState: [WritableState], allowHalfOpen: false, _sockname: null, _pendingData: null, _pendingEncoding: '', server: null, _server: null, parser: null, _httpMessage: null, timeout: 0, [Symbol(async_id_symbol)]: 1579, [Symbol(kHandle)]: [TCP], [Symbol(kSetNoDelay)]: true, [Symbol(lastWriteQueueSize)]: 0, [Symbol(timeout)]: null, [Symbol(kBuffer)]: null, [Symbol(kBufferCb)]: null, [Symbol(kBufferGen)]: null, [Symbol(kCapture)]: false, [Symbol(kBytesRead)]: 0, [Symbol(kBytesWritten)]: 0, [Symbol(RequestTimeout)]: undefined, [Symbol(websocket)]: [Circular *1] }, _bufferedAmount: 0, _isServer: false, _redirects: 0, _url: 'ws://127.0.0.1:4444', _req: null, [Symbol(kCapture)]: false }, type: 'message', data: '{"sourceKind":"ffmpeg_source","sourceName":"<Media_Source_03>","update-type":"MediaEnded"}' }`

`2022-02-25T20:26:42.394Z obs-websocket-js:Socket [emit] MediaEnded err: { sourceKind: 'ffmpeg_source', sourceName: '<Media_Source_03>', 'update-type': 'MediaEnded', updateType: 'MediaEnded' } data: undefined`

`MEDIA ENDED FOR SOURCE <Media_Source_03>` <-- debug from the obs module


***** ERROR CASE
`2022-02-25T20:26:28.004Z obs-websocket-js:Socket [OnMessage]: MessageEvent { target: <ref *1> WebSocket { _events: [Object: null prototype] { error: [Function], open: [Function], close: [Function], message: [Function] }, _eventsCount: 4, _maxListeners: undefined, _binaryType: 'nodebuffer', _closeCode: 1006, _closeFrameReceived: false, _closeFrameSent: false, _closeMessage: '', _closeTimer: null, _extensions: {}, _protocol: '', _readyState: 1, _receiver: Receiver { _writableState: [WritableState], _events: [Object: null prototype], _eventsCount: 6, _maxListeners: undefined, _binaryType: 'nodebuffer', _extensions: {}, _isServer: false, _maxPayload: 104857600, _bufferedBytes: 7062, _buffers: [Array], _compressed: false, _payloadLength: 90, _mask: undefined, _fragmented: 0, _masked: false, _fin: true, _opcode: 1, _totalPayloadLength: 0, _messageLength: 0, _fragments: [], _state: 4, _loop: true, [Symbol(kCapture)]: false, [Symbol(websocket)]: [Circular *1] }, _sender: Sender { _extensions: {}, _socket: [Socket], _firstFragment: true, _compress: false, _bufferedBytes: 0, _deflating: false, _queue: [] }, _socket: Socket { connecting: false, _hadError: false, _parent: null, _host: null, _readableState: [ReadableState], _events: [Object: null prototype], _eventsCount: 4, _maxListeners: undefined, _writableState: [WritableState], allowHalfOpen: false, _sockname: null, _pendingData: null, _pendingEncoding: '', server: null, _server: null, parser: null, _httpMessage: null, timeout: 0, [Symbol(async_id_symbol)]: 1579, [Symbol(kHandle)]: [TCP], [Symbol(kSetNoDelay)]: true, [Symbol(lastWriteQueueSize)]: 0, [Symbol(timeout)]: null, [Symbol(kBuffer)]: null, [Symbol(kBufferCb)]: null, [Symbol(kBufferGen)]: null, [Symbol(kCapture)]: false, [Symbol(kBytesRead)]: 0, [Symbol(kBytesWritten)]: 0, [Symbol(RequestTimeout)]: undefined, [Symbol(websocket)]: [Circular *1] }, _bufferedAmount: 0, _isServer: false, _redirects: 0, _url: 'ws://127.0.0.1:4444', _req: null, [Symbol(kCapture)]: false }, type: 'message', data: '{"sourceKind":"ffmpeg_source","sourceName":"<Media_Source_02>","update-type":"MediaEnded"}' }`

`2022-02-25T20:26:28.004Z obs-websocket-js:Socket [emit] MediaEnded err: { sourceKind: 'ffmpeg_source', sourceName: '<Media_Source_02>', 'update-type': 'MediaEnded', updateType: 'MediaEnded' } data: undefined`

**Comment by bryce-seifert** [comment]
Media variables have been rewritten for 5.0.0. Let me know if this issue persists with the latest [beta builds of Companion](https://bitfocus.io/companion/download/builds/)
