### ISSUE TITLE
Source visible in program with nested scene

### ISSUE THREAD

**Issue by MatDepInfo** [bitfocus/companion-module-obs-studio#151]
Hello,
I got a scene (scene 1) with inside a nested scene (scene 2). I manage visibility of each sources in the nested scene (scene 2). But with Companion, impossible to get information about the visibility of this source in the program accross the main scene (scene 1). I try "OBS: Source Visible in Program" but first, it's not working correctly and second, the source is in use in several others scenes so it's not exactly what I'm looking for. Do you have any solution ?

**Comment by bryce-seifert** [comment]
Hey there, I can definitely take a look at this. As a note, I'm currently rewriting the whole module for obs-websocket 5.0 so it may be a bit. But, there are lots of improvements with 5.0 and visibility accuracy. And I'll look differentiating between a source in multiple scenes.

**Comment by MatDepInfo** [comment]
Perfect, let me informed. If you need held, don't hesitate !

**Comment by bryce-seifert** [comment]
@MatDepInfo Source visibility should be improved with the rewrite for websockets 5.0. This is now available in the [beta builds of Companion](https://bitfocus.io/companion/download/builds/). You can also now specify a scene as well
<img width="595" alt="Screen Shot 2022-08-15 at 6 58 01 AM" src="https://user-images.githubusercontent.com/50299051/184631281-c5df92ea-2040-4cc1-9616-8698ad1a5c00.png">

**Comment by MatDepInfo** [comment]
Hello, in fact, always the same problem:
Scene 2 into scene 1. Source A in scene 2 visible in program.
If i set scene 1 source A, feedback works. I f i set scene 2 source A, feedback not working.

**Comment by bryce-seifert** [comment]
That would make sense with how this is set up, as the "Scene" option in the feedback refers to the scene that is listed as Program in OBS. And since Scene 1 is the main scene in program, that is what it is checking against.

**Comment by MichaelGame-Dev** [comment]
@bryce-seifert  maybe I need a new issue for this one.
But I have a nested scene that contains my camera called "circle camera" I have that as a source in my main scene: Screen with camera Right.

For the action, I have toggle source visibility. I have current scene selected so the action works in any scene. I then select the source as circle camera.
This works to affect the toggling of circle camera.

However, when I change to feedback, I select Source visible in program. If I select circle camera here, I get basically no change.

![Image](https://github.com/user-attachments/assets/4bec7dea-84b5-41db-b0bf-7bb611c8d47c)

If I update the source the feedback is checking to Sony ZV-E10 (which is the base source in "Circle Camera") then I can get the green to come up, but not the red. Any suggestions?

![Image](https://github.com/user-attachments/assets/923b82a7-860f-4c6c-9988-8361b3b87ce1)

**Comment by bryce-seifert** [comment]
> [@bryce-seifert](https://github.com/bryce-seifert) maybe I need a new issue for this one. But I have a nested scene that contains my camera called "circle camera" I have that as a source in my main scene: Screen with camera Right.
> 
> For the action, I have toggle source visibility. I have current scene selected so the action works in any scene. I then select the source as circle camera. This works to affect the toggling of circle camera.
> 
> However, when I change to feedback, I select Source visible in program. If I select circle camera here, I get basically no change.
> 
> ![Image](https://github.com/user-attachments/assets/4bec7dea-84b5-41db-b0bf-7bb611c8d47c)
> 
> If I update the source the feedback is checking to Sony ZV-E10 (which is the base source in "Circle Camera") then I can get the green to come up, but not the red. Any suggestions?
> 
> ![Image](https://github.com/user-attachments/assets/923b82a7-860f-4c6c-9988-8361b3b87ce1)

**Comment by bryce-seifert** [comment]
@MichaelGame-Dev Thanks for the info, I think I understand your setup. My best guess is this is two issues:
1) for never seeing the red feedback, can you try reordering the Program feedback to be below the Preview? Companion will always report the bottom most true feedback in a stack, so I’m wondering if the preview is overriding that.

2) I think when trying to use “Circle camera” scene it’s related to this issue https://github.com/bitfocus/companion-module-obs-studio/issues/179 , where OBS is not reporting info about Scenes within scenes. Which would explain why it’s working for the root source, but not the scene.

Let me know if item one makes program feedback work, and I’ll try to bump item 2 in the upstream OBS issue

**Comment by MichaelGame-Dev** [comment]
> for never seeing the red feedback, can you try reordering the Program feedback to be below the Preview? Companion will always report the bottom most true feedback in a stack, so I’m wondering if the preview is overriding that.

For 2, I went ahead and changed them to the source under the scene.

Hmm I don't have anything about preview in the settings (I'm only using program). What I see is the button is either green or black (the base color). That is really good to know about the bottom one.

If you mean my OBS screenshot, I think there are two scenes showing in blue because that's what my mouse was hovering over when activating the screenshot feature.

**Comment by bryce-seifert** [comment]
> Hmm I don't have anything about preview in the settings (I'm only using program).

Sorry that is my mistake, I think I misread one of the feedbacks. Either that or my brain can't break the preview = green color association 🧠 💥
