### ISSUE TITLE
Using companion internal variables for scenes

### ISSUE THREAD

**Issue by Mill-Sound** [bitfocus/companion-module-obs-studio#152]
Please implement usage of internal variables for preview scene, program scene and smart scene switcher. I would like to be able to use an internal variable as part of a scene name. for example: scene 'camera 1' and scene 'frame camera 1'  where frame is the content of an internal variable. The variable is empty or filled with frame.

**Comment by bryce-seifert** [comment]
@Mill-Sound This is now available in the [beta builds of Companion](https://bitfocus.io/companion/download/builds/). Please note this requires obs-websocket 5.0.0. 
<img width="594" alt="Screen Shot 2022-08-15 at 6 55 21 AM" src="https://user-images.githubusercontent.com/50299051/184631035-08d87bb4-d2d1-4600-b4e0-f6134d83978d.png">
