### ISSUE TITLE
Incompatible with OBS Websocket 5.0.0

### ISSUE THREAD

**Issue by SaabFAN** [bitfocus/companion-module-obs-studio#153]
The new Websocket-Version 5.0.0 has implemented a new protocol, which makes this Plugin incompatible unless the Compatibility-Layer is installed. 
Is there a plan to implement compatibility for the new protocol in the near future?

**Comment by bryce-seifert** [comment]
There is! I’m about 90% done with the implementation, and hope to have it in beta soon. I’m just tying up some things with the websockets developers that I’m hoping they can patch before release.


So you happen to be on Mac? I can send you a build if you’d like to test a pre-release

**Comment by LGCW** [comment]
Ran into the 5.0 compat issues while playing OBS 28 beta this afternoon. Websockets is built in now. Constantly disconnects / reconnects. 

This is with 2.3.0 running on a Pi in the studio.

**Comment by bryce-seifert** [comment]
Now that OBS 28 beta is out I expect more people on 5.0

I’m going to try and get the updated into beta by end of week as well so we can begin testing

**Comment by bryce-seifert** [comment]
obs-websocket 5.0.0 / OBS 28 support is now available in the [beta builds of Companion](https://bitfocus.io/companion/download/builds/). Please keep in mind this is a beta, so back up your config before trying it. Please let me know of any problems you find by opening an issue, or reaching out on Slack. @LGCW @SaabFAN
