### ISSUE TITLE
"Current Media" Source for media controls

### ISSUE THREAD

**Issue by DachsbauTV** [bitfocus/companion-module-obs-studio#155]
Hey everyone,

It would be great to have the option to choose the "current media" instead of having to choose a specific media source for control actions.

There is a "current media" variable already so I'm hoping this isn't too much work either.

This would eleminate the need for creating a button for every single media item for e.g. pause the clip

**Comment by bryce-seifert** [comment]
I'll look at adding this to the 5.0 rewrite

**Comment by bryce-seifert** [comment]
@DachsbauTV This is now available in the [beta builds of Companion](https://bitfocus.io/companion/download/builds/).

**Comment by DachsbauTV** [comment]
You are amazing
