### ISSUE TITLE
Set recording settings

### ISSUE THREAD

**Issue by flvlef** [bitfocus/companion-module-obs-studio#160]
As I see that Set Stream Settings is available, I'm wondering if the fact that there is now way to Set Recording Settings is a limitation of this module or the OBS Websocket implementation.
FYI I'm running on `companion-module-obs-studio v2` and `OBS v28 RC2`

**Comment by bryce-seifert** [comment]
There's no native way to do it with OBS websockets. I think we may be able to adjust a limited number of settings by changing the profile directly. I'm going to look more into that, and have also reached out to the OBS websocket folks to see what they say. What specific settings are you looking to adjust in the recording settings? That will help guide the route I take with implementing this.

**Comment by flvlef** [comment]
Hello @bryce-seifert ,
Thank you.
In my context the only dynamic setting would be the recording output URL.
I use the Avanced Recording > ffmpeg mode > URL-type output.

The heavier approach would be to produce a whole Profile dynamically, then push it on the OBS machine, then send the command to load this specific one via OBS websocket. I seems to be quite heavy to only adjust a URL 😅.
Thanks

**Comment by bryce-seifert** [comment]
It looks like the FFmpeg URL is exposed in the profile.
So, you could use the Custom Command action and make the request typ
`SetProfileParameter`
and the Request Data:
`{"parameterCategory": "AdvOut", "parameterName": "FFURL", "parameterValue": "http://testing.com"}`

I'll try to see if there's a nicer way to do this, but the above worked for me in testing

**Comment by flvlef** [comment]
Thank you @bryce-seifert it just work perfectly!
