### ISSUE TITLE
Filters for Scenes not working

### ISSUE THREAD

**Issue by richardguenther** [bitfocus/companion-module-obs-studio#161]
Hi,

since the new update for obs 28 (and the change to obs-websockets 5.0.1) it is no longer possible to see or activate filters, that are set on Scenes. (Filters for Sources are still working)

I looked at the obs-websockets documention and don't see at first glance which new command has caused this.

Even if I nest the scene as a source in another scene it doesn't work.

Filters on Scenes are one way how I use the move-transition from exeldro. 

Touch Portals Websockets5 - integration shows filters on Scenes (and on Sources).

thanks for your work!
richard

**Comment by bryce-seifert** [comment]
It looks like I missed scene filters. I've got a fix in the works, going to to a little more testing and then get it in beta

**Comment by bryce-seifert** [comment]
This should be fixed in the latest [beta builds](https://bitfocus.io/companion/download/builds/) of Companion

**Comment by richardguenther** [comment]
Hi - that was amazingly quick. I tried it on the windows build and it works. Thank you!
