### ISSUE TITLE
Latest rewrite breaks using multiple instances

### ISSUE THREAD

**Issue by thedist** [bitfocus/companion-module-obs-studio#162]
The rewrite to this module made changes that went from using instance specific connections, to a global `obs` variable.

Because the `obs` variable is global, when each instance calls `connectOBS` it kills any existing connection to start a new one. This is a significant breaking change and makes the module unusable by anyone needing to connect to multiple OBS servers.

The fix would be to have the connection to OBS as part of the instance class, this way each instance would have its own connection that is independent of all others.

**Comment by bryce-seifert** [comment]
Thanks for bringing this to my attention. I have a [fix](https://github.com/bryce-seifert/companion-module-obs-studio/tree/fix/globalVariable), will hopefully get it merged this weekend with some other fixes

**Comment by bryce-seifert** [comment]
@thedist This should be fixed in the latest beta

**Comment by kjetilpp** [comment]
Is this the reason to why i get "New WebSocket connection" every 1 sec?

**Comment by bryce-seifert** [comment]
@kjetilpp Can you be more specific? Are you seeing this notification in OBS or Companion?
Are you using the [latest beta](https://bitfocus.io/companion/download/builds/) of Companion?

**Comment by kjetilpp** [comment]
@bryce-seifert In OBS/Windows
![Screenshot 2022-09-05 021456](https://user-images.githubusercontent.com/5620578/188339102-435a5968-7228-4915-8496-7a16a1c5db5c.png)
Did run a beta update like 12h ago. Started after that.

**Comment by bryce-seifert** [comment]
Interesting, not sure why this would be.

What version of Companion were you using before the update?

Also are there any errors in the Companion  > Logs tab?

**Comment by kjetilpp** [comment]
What version of Companion were you using before the update?
Not sure, maybe 2.2.X?  Think is was from around month 04 or 05,
No errors in the Companion > Logs tab.

**Comment by bryce-seifert** [comment]
Ok, and are you using OBS 28 / OBS websockets 5.0.0?

**Comment by rgischig** [comment]
In order to have OBS 28 to work, you need to use a beta-companion version. the official 2.3 does not support OBS28 (WebSockets 4.9).
My Raspy is almost craashing as it seams to poll very frequent and fails to connect.
