### ISSUE TITLE
not able to choose scene in send to projector action

### ISSUE THREAD

**Issue by Spekko1980** [bitfocus/companion-module-obs-studio#165]
Note that this is in the companion-win64-2.4.0+4679-beta-ec05abcd version.

When using the obs: Open Projector action and setting Projector Type to Scene, I cannot select Scenes, it only shows sources.
We had to move to the beta version because our IT updated OBS to 28 which led to a connection error which is resolved in the beta version.

Just checked in [2.3.0 (2.3.0+4608-v2-3.0-2994a6d0)]. In that version scenes as well as sources are shown and selectable.

**Comment by bryce-seifert** [comment]
Sorry about that, I see the issue. I will try and get it fixed very soon.

If you need an immediate fix, one possible way around is if you add the scene into another scene as a source, you should be able to select it.

**Comment by bryce-seifert** [comment]
@Spekko1980 This is now fixed in the latest beta. Let me know if there are any issues!
