### ISSUE TITLE
Bug: Change colors when source visible exclusivity

### ISSUE THREAD

**Issue by B00TK1D** [bitfocus/companion-module-obs-studio#17]
When adding the "Change colors when source visible" instance feedback to a button, it does not retain its value when a different source's visibility is toggled.

Usage: I have a set of overlays (Overlay 1, Overlay 2, etc.) in each camera scene.  I created a corresponding set of buttons which toggle the visibility of the appropriate overlay in each camera scene.  I then added an instance feedback to each button which changes the button's background color when that overlay is visible, allowing easy monitoring of which overlays are currently active.  If I start with all overlays off, then press the button for Overlay 1, it turns on in all camera scenes and its background changes, as expected.  If I then press the button for Overlay 2, that overlay turns on in all camera scenes and its background changes as expected.  However, at the same time, Overlay 1's button background reverts to original.  This is the problem.

**Comment by bryce-seifert** [comment]
Should be fixed with https://github.com/bitfocus/companion-module-obs-studio/pull/20

**Comment by eric** [comment]
Can this be closed?
