### ISSUE TITLE
Connection failure to OBS

### ISSUE THREAD

**Issue by ianreeder** [bitfocus/companion-module-obs-studio#170]
Last night my OBS version was updated to V28 and bitfocus companion started giving Java errors on the application launch and then failed to connect to OBS.  After much testing I've completely removed OBS and all settings along with companion.  I reinstalled the newest version OBS and newest version of companion and I'm getting errors when connecting.  I've enabled the websocket connection in OBS and confirmed the port and disabled the password.  The Companion connection keeps flashing between "OK," "Connecting" and "ERROR".  I attached a screen shot in a brief moment that it says "OK" but it never does successfully connect.  There's also a websocket sessions that pops up once every 10 seconds or so and then immediately disappears from OBS, I took the screen shot in the moment it appeared.  I'm using localhost as my IP.  Any suggestions would be appreciated! 

![connectionfailure](https://user-images.githubusercontent.com/20866668/190170148-b951bf12-5ba6-44ce-94e7-234e5193d2bd.png)

**Comment by bryce-seifert** [comment]
Support for OBS 28 is available in the [beta builds of Companion](https://bitfocus.io/companion/download/builds/).

**Comment by ianreeder** [comment]
Thank you! I'll try that first.  If I have trouble, do you recommend I revert to OBS 27?

**Comment by bryce-seifert** [comment]
You can do that, or you may be able to install [obs-websocket 4.9.1-compat](https://github.com/obsproject/obs-websocket/releases) and keep using OBS 28. The thing that's causing the issue is OBS 28 comes with websocket 5.0, which we have support for but it's still in beta.
