### ISSUE TITLE
Problems updating

### ISSUE THREAD

**Issue by ZachRosing** [bitfocus/companion-module-obs-studio#171]
I'm having trouble getting the current version of this module installed that will work with OBS 28, even though I have Companion 2.3.1 installed. Can you help explain how to manually update this module? I'm using a raspberry pi. Thanks!

**Comment by bryce-seifert** [comment]
I don't personally use a Pi, but you may be able to run

`sudo companion-update beta`
Or possibly just

`sudo companion-update` and then select the beta version. Sorry I'm unable to test this.

**Comment by bryce-seifert** [comment]
@ZachRosing Were you able to get this updated to the beta, and if so is it working with v28?

**Comment by alomantofl** [comment]
How would you go about performing this companion-update command on windows?

**Comment by alomantofl** [comment]
I did that and the plugin still seems to be out of date, see screenshots below. It's possible that I've missed something but I can confirm the settings are correct, it's failing in the log and I see the connection failing in the websocket log as it's trying to use the legacy websocket authentication.

![image](https://user-images.githubusercontent.com/72946135/193175286-0b7d09dd-c037-4de1-8bcb-be569d3c4a23.png)

![image](https://user-images.githubusercontent.com/72946135/193175360-18a68d99-23fd-4452-beae-5834efad55ec.png)

![image](https://user-images.githubusercontent.com/72946135/193175417-0f0e67f2-07f5-447c-965c-673d62b1ccce.png)

![image](https://user-images.githubusercontent.com/72946135/193175499-06f72233-dfd1-46da-9bd1-16e16ed3d84d.png)

**Comment by bryce-seifert** [comment]
@alomantofl Make sure to navigate to the "Beta Builds" page in order to download a version that supports the new obs-websocket.

When you open Companion, the version number should be 2.4.0

<img width="782" alt="Screen Shot 2022-09-29 at 9 52 52 PM" src="https://user-images.githubusercontent.com/50299051/193180077-2d8f0a8c-d573-45e5-984e-c8d94a5b3214.png">

**Comment by alomantofl** [comment]
Ah, I see what happened. I did download the beta last time, but apparently I either managed to run the old installer or the beta installer failed and I didn't notice, as I re-downloaded, ran it and it worked. I didn't look closely at the version number last time and just assumed I was running the beta version. Thanks so much!
