### ISSUE TITLE
Unable to Connect Companion to OBS 28

### ISSUE THREAD

**Issue by apisandipas** [bitfocus/companion-module-obs-studio#172]
Hello, 

When I try to enable the OBS connection it flickers back and forth begin OK and Error. The Companion log fills up with "instance(obs): Connection lost to OBS." repeatedly.

I am running Companions 2.3.1 and OBS 28. My understanding is that these versions are compatible as the module indicates support for the obs-websocket 5.0+ protocol. When I enable debug logging for the web-socket connection. It will briefly flash up on the screen with an X under the identified column. I am running the latest updates from Endeavor OS.

**Comment by bryce-seifert** [comment]
Support for OBS 28 is available in the [beta builds of Companion](https://bitfocus.io/companion/download/builds/).
