### ISSUE TITLE
Doesn't detect disconnection in v28

### ISSUE THREAD

**Issue by nick-potts** [bitfocus/companion-module-obs-studio#173]
it currently silently disconnects without the module detecting. Under connections, it'll say status = "OK", but the only way to fix is disabling and enabling the module. If it helps, I run 3 instances of the module in my setup.

**Comment by bryce-seifert** [comment]
I can look into this.

What version of Companion are you using?

**Comment by nick-potts** [comment]
![image](https://user-images.githubusercontent.com/1109914/191416599-b7463264-fa88-4c60-af39-6ba355cb8a3f.png)
![image](https://user-images.githubusercontent.com/1109914/191416626-3805e2c9-8e12-459f-9758-51d8352a7127.png)
![image](https://user-images.githubusercontent.com/1109914/191416707-61eb6786-3abd-47dc-a423-981aca04df35.png)


In the logs it knows it doesn't have a connnection, however in the main it still says ok.

**Comment by bryce-seifert** [comment]
That is odd behavior.

I think the first step is to figure out what's causing the disconnect initially. I'm assuming OBS is still open and online?  Would you be able to, via Slack, send me files from the Companion > Log > Export Support Bundle after a disconnect happens?

**Comment by bmaccollum** [comment]
I am not any type of developer, just trying to trouble shoot an issue.
My set up is very minimal but I just updated my Companion software, Blackmagic Design ATEM software as well as the OBS software and I no longer can connect to OBS. Any help is appreciated. 
![image](https://user-images.githubusercontent.com/114119348/191633473-d8a87126-b09c-4c55-ae3a-d1dd55c09bf2.png)

**Comment by bryce-seifert** [comment]
@bmaccollum If you updated to OBS 28, you will need to download one of the [beta builds of Companion](https://bitfocus.io/companion/download/builds/) to connect.

**Comment by nick-potts** [comment]
> I think the first step is to figure out what's causing the disconnect initially. I'm assuming OBS is still open and online? Would you be able to, via Slack, send me files from the Companion > Log > Export Support Bundle after a disconnect happens?

The OBS gets closed as its an always on Stream PC with seperate OBS's for streaming/recording. The issue is that it still thinks its connected, and then when OBS is relaunched it never reconnects.

**Comment by bryce-seifert** [comment]
@nick-potts I think I was able to replicate this by force quitting OBS on Mac (instead of through the menu). I'm working on a fix now

**Comment by bryce-seifert** [comment]
@nick-potts I'm hopeful this is fixed in the latest beta builds of Companion. Let me know if not!
