### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by davisa6477** [bitfocus/companion-module-obs-studio#177]
How do I install this update or source code?

**Comment by bryce-seifert** [comment]
@davisa6477 Are you referring to support for OBS 28 (websocket 5.0)?

You can download a beta build from the [Bitfocus site](https://bitfocus.io/companion/download/builds/)
The version number should be 2.4.0
<img width="782" alt="193180077-2d8f0a8c-d573-45e5-984e-c8d94a5b3214" src="https://user-images.githubusercontent.com/50299051/193358858-ce251b65-bcc8-4c58-b807-57434fd2feb2.png">
