### ISSUE TITLE
OBS Companion debug log full of 

### ISSUE THREAD

**Issue by sdmoore68** [bitfocus/companion-module-obs-studio#180]
I rolled back to WebSockets to 4.9.1 and OBS to 27.2.4 (64-bit, windows).  I am not sure when it started but Companion is spewing critical entries in thee log every second.

22.10.09 16:51:12 instance(obs): Media time remaining parse error: RangeError: Invalid time value
22.10.09 16:51:11 instance(obs): Media time remaining parse error: RangeError: Invalid time value
22.10.09 16:51:10 instance(obs): Media time remaining parse error: RangeError: Invalid time value
22.10.09 16:51:09 instance(obs): Media time remaining parse error: RangeError: Invalid time value
22.10.09 16:51:08 instance(obs): Media time remaining parse error: RangeError: Invalid time value
22.10.09 16:51:07 instance(obs): Media time remaining parse error: RangeError: Invalid time value
22.10.09 16:51:06 instance(obs): Media time remaining parse error: RangeError: Invalid time value

**Version Information:**
- Operating System: Windows 10
 - OBS app: 27.2.4
 - obs-websocket: 4.9.1
 - Companion:2.3.0+4608-v2-3.0-2994a6d0

**Comment by bryce-seifert** [comment]
Sorry, slightly confused, what version did you rollback from?

This is likely result of this fix https://github.com/bitfocus/companion-module-obs-studio/commit/8d15877ef0e0bf4ab01ced8d2a7302ed2655b64c

However, this should all be moot with OBS 28 / Companion 2.4 beta

**Comment by sdmoore68** [comment]
I had to roll back from OBS 28 due to plugin incompatibility.

-----
Regards,
Sid Moore

Proverbs 3:3 Let love & faithfulness never leave you; bind them around your
neck, write them on the tablet of your heart.Then you will win favor & a
good name in the sight of God & man.

**Comment by bryce-seifert** [comment]
@sdmoore68 Got it. Right now the only real option is you could:

1. Upgrade obs-websocket by itself to 5.0.1 using [this installer](https://github.com/obsproject/obs-websocket/releases/tag/5.0.1), and continue using OBS 27. 
2. Use a beta build of companion (version 2.4) that is compatible with  obs-websocket 5

This should prevent the error in the log

**Comment by sdmoore68** [comment]
Got it, thanks! My plan is to upgrade next week.

As far as I know, storage from the growing logs are the only resources that
are getting abused.  Are there other resources I should monitor until
then?  Can I delete the log?

-----
Regards,
Sid Moore

Proverbs 3:3 Let love & faithfulness never leave you; bind them around your
neck, write them on the tablet of your heart.Then you will win favor & a
good name in the sight of God & man.

**Comment by bryce-seifert** [comment]
I don't think there should be any other concerns resource-wise.

Let me know if you have any issues after the upgrade!
