### ISSUE TITLE
Group Source Visibility

### ISSUE THREAD

**Issue by atscomms** [bitfocus/companion-module-obs-studio#181]
Let's say I group sources within an OBS scene and name the group, and I manually select certain sources within the group as visible.
When I set a button to Toggle Source Visibility and I select the Group Name, that button currently toggles all the sources in the group.

I would like it to toggle ONLY the group visibility (by group name), and not affect the visibility of the sources within the group.

Use Case- Grouping Lower 3rd slides for a number of presenters. I would like to manually preselect the slide (or slides) for the current presenter(s), and toggle the group's visibility with a Companion button.

Thank you!

**Comment by bryce-seifert** [comment]
@atscomms This should be fixed I the latest Companion beta release (https://github.com/bitfocus/companion-module-obs-studio/pull/182)
