### ISSUE TITLE
Scenes with similar names

### ISSUE THREAD

**Issue by atscomms** [bitfocus/companion-module-obs-studio#184]
I have two OBS scenes named "Z no Slides" and "Z with Slides". I have other scenes as well
In Companion's Set Preview Scene /Set Program Scene buttons, only one (or neither) of these scenes will be available to choose from. All other scenes are available.

**Version Information:**
- Operating System: Windows 10
 - OBS app: 27.2.4
 - obs-websocket: 5.0.1
 - Companion: [2.4.0 (2.4.0+4729-beta-01d43973)](https://bitfocus.io/companion/)

**Comment by atscomms** [comment]
These OBS Scenes seems to be disappearing in Companion until I rename them, and then they might disappear again.

**Comment by bryce-seifert** [comment]
Are you switching between scene collections, or does this happen while using one scene collection? Is there any particular action / event that causes a scene to disappear or is it random?

**Comment by atscomms** [comment]
Just one scene collection. Not doing anything I can identify as a cause.

*Marty *

**Comment by atscomms** [comment]
Just one scene collection. To clarify, the OBS Scenes are still there,  it is Companion that has either lost the ability to control them (??), or to show them in the list.However,  Companion does show me scenes that were indeed removed from OBS intentionally. Dies Companion get scene data from obs periodically, or only when a change occurs? Thank youSent from my Veri Sammy Galaxy
-------- Original message --------From: bryce ***@***.***> Date: 10/25/22  6:31 PM  (GMT-05:00) To: bitfocus/companion-module-obs-studio ***@***.***> Cc: atscomms ***@***.***>, Author ***@***.***> Subject: Re: [bitfocus/companion-module-obs-studio] Scenes with similar names
  (Issue #184) 
Are you switching between scene collections, or does this happen while using one scene collection? Is there any particular action / event that causes a scene to disappear or is it random?

**Comment by bryce-seifert** [comment]
Companion updates scene data on connection, and then when scenes are removed, created, or renamed.

I'm curious, have you tried seeing if this issue happens on OBS 28? I've been trying to replicate with those scene names but have not had success yet with v28.

**Comment by atscomms** [comment]
I have to stay on 27 until NDI is working on 28.
Would it help if I send you the OBS scene collection and Companion page?
Now that the event is over and I've shut OBS down, I'll be curious to see if the removed scenes will still be listed in Companion.
I'll report back.

**Comment by atscomms** [comment]
Now it is working, however it worked for a time when I set it up.
Double ?? is an indication of a lost websocket connection, however some of the buttons did work. I did not check the status at the time.
So I have to let the source/scene availability question go for now, but the similar scene name question is still open.
Thank you

**Comment by bryce-seifert** [comment]
@atscomms Are you still having issues with similar scene names? I have not been able to recreate in OBS 27 or 28.
If so, would you mind sending your Scene Collection?

**Comment by atscomms** [comment]
I am not able to recreate it now either. Scenes with the same names in the OP both show in the scene list for buttons.
I'll close this issue for now,
Thank you
