### ISSUE TITLE
Sources not showing in Companion when OBS Group name has a space...

### ISSUE THREAD

**Issue by UWSCIA** [bitfocus/companion-module-obs-studio#185]
**Describe the bug**
While auditing triggers and buttons with the "beta" companion version as I needed the variable phrasing and newer websocket...
I noticed not all Text sources were listed...
I changed the name to remove spaces as this is normally the issue, but previous version didn't have this issue... didn't work...
Then realized all the missing Text sources were in a Group, Changed the Group name to remove spaces... all Text Sources Showed up even the ones with spaces...

**To Reproduce**
1. Rename Group name with Text Sources in it to have a space
2. Relaunch Companion... all Text Sources within Companion from that group gone.
3. Rename Group name to have no spaces.. all Text Sources within Companion from that group return even if the text source has a space in the name...

**Version Information:**
- Operating System: POP_OS 22.04
 - OBS app: 28.1.1
 - obs-websocket: 5.0.1
 - Companion: 2.4.0+4760

**Comment by bryce-seifert** [comment]
I was able to recreate this and find the issue. It seems like some text sources weren't being properly pushed to the choices on startup (even though they were being recognized, as they appeared as a variable). I should have a fix for this in the next release
