### ISSUE TITLE
OBS v28 Websocket v5 Connectivity Bug

### ISSUE THREAD

**Issue by DerNephias** [bitfocus/companion-module-obs-studio#189]
Companion is loosing the Websocket connection to the newest OBS Version. 
[companion_log_20221122-0945.csv](https://github.com/bitfocus/companion-module-obs-studio/files/10065561/companion_log_20221122-0945.csv)

**Comment by bryce-seifert** [comment]
In order to use OBS 28 / obs-websockets 5, you need to download the Companion beta build (v2.4)
