### ISSUE TITLE
Usage guide

### ISSUE THREAD

**Issue by gdhgdhgdh** [bitfocus/companion-module-obs-studio#19]
After trying with both the native Node 8 in Ubuntu 20.04, and the latest Node 14.4 from Docker Hub I get the following after a successful `npm install`

```
root@b58957a4d8c4:/host# node index.js 
internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module '../../instance_skel'
Require stack:
- /host/index.js
```

What am I missing? I hoped `instance_skel` was another node module, but seemingly not:

```
root@b58957a4d8c4:/host# npm s instance_skel
No matches found for "instance_skel"
```

**Comment by bryce-seifert** [comment]
Are you trying to run this module by itself? Or are you trying to run Companion?

**Comment by gdhgdhgdh** [comment]
I'm trying to run it standalone. I'm going to guess that's the problem - I'll try it in the context of Companion.

**Comment by bryce-seifert** [comment]
@gdhgdhgdh Yes, it will need to be run through Companion as the module relies on that framework. Did you get it running?

**Comment by gdhgdhgdh** [comment]
I haven't tried and don't know when I'll have time to - I'll close this issue :)
