### ISSUE TITLE
add Scene Name variables corresponding to current order of Scene Collection

### ISSUE THREAD

**Issue by jorgepablot** [bitfocus/companion-module-obs-studio#191]
Like the VLC module playlist name variable "$(vlc:pname_1)", it would be great if obs-studio module can get scene name variables corresponding to their current order in the scene collection. This would allow for easier setup and monitoring of scene names in Companion, and would speed up and standardize some workflows that take into account scene order.

**Comment by bryce-seifert** [comment]
Initial support for this was added with https://github.com/bitfocus/companion-module-obs-studio/commit/6af603f1a4439c2ec1c7a2a08515eb61ec9e7e9, which will be available with companion v3.

One note, is obs-websocket currently does not fire an event when the scene order is changed. It's listed as a to-do. So, this won't be entirely accurate until that's resolved, but it will change when changing collections.
