### ISSUE TITLE
OBS Preview and Program Companion 3

### ISSUE THREAD

**Issue by IceCubeNinJah** [bitfocus/companion-module-obs-studio#200]
Kinda of new to all this. Obs Module worked normally with Companion 2.
With companion 3 the module doesnt let me set preview. Everything goes live to program.
Tried to mod some buttons, but I think I might just be missing a witch?
Not sure if this is an issue with other people

Thanks
Bobby IceCube G.

**Comment by bryce-seifert** [comment]
@IceCubeNinJah Good catch. This was a typo on my part. I've fixed the error, and this will be in a future v3 beta.
