### ISSUE TITLE
Feedback option for Studio Mode Active

### ISSUE THREAD

**Issue by alomanto** [bitfocus/companion-module-obs-studio#203]
It would be great to have a "Studio Mode Active" feedback option as there is for streaming, recording, etc. The websocket does explicitly have an option to check this. 

There is already an option to check if a source or scene is in preview, but if all you care about is if Studio Mode is active or not (and not about a specific scene or source), there is no explicit option for this that I can see in the Bitfocus feedback list for OBS. 

The "Source active in preview" feedback only checks to see if a source is active on the current scene (as far as I can see) and will not trigger if that source is in a nested scene that is technically active, but not in the source list. 

The "Scene in Preview / Program", again, only checks to see if the scene you set is explicitly selected and does not take into account nested scenes. For the time being, I am adding multiple of this feedback item to a button, each with every scene that I could feasibly switch to, in order to give me exactly what i'm looking for.

**Comment by bryce-seifert** [comment]
Thanks for the suggestion! I've added this feature, and it will be included in a future release of the Companion v3 beta
