### ISSUE TITLE
SET PREVIEW SCENE RUN SET PROGRAM SCENE

### ISSUE THREAD

**Issue by SOSF-Regie** [bitfocus/companion-module-obs-studio#204]
**Describe the bug**
When I set OBS: Set Preview Scene in companion, it runs like if i setted OBS: Set Program Scene

**Version Information:**
OBS Version: 29.02
Companion Version: 3.0.0

**Comment by bryce-seifert** [comment]
Hello, this bug is fixed in the latest 3.0 beta available on the Bitfocus site
