### ISSUE TITLE
Feat: Add button style properties to "Scene in Preview / Program" feedback.

### ISSUE THREAD

**Issue by nacalai** [bitfocus/companion-module-obs-studio#207]
I want to style a button with PNGs depending on if a scene is in preview / program. This is not possible with the "Scene in preview / program" feedback. I have to resort to using both "Source active in preview" and "Source visible in program" to accomplish what I want.

![image](https://user-images.githubusercontent.com/4357694/227326200-238f485d-ec3c-440c-84f7-f54d6ec5e8f5.png)

Add button style properties to the scene preview/program-feedback, and/or add separate "Scene in preview / program" feedbacks which include button styles. I mentioned the latter, because I assume you maybe can't incorporate two button styles in one feedback.

**Comment by bryce-seifert** [comment]
This is taken care of with https://github.com/bitfocus/companion-module-obs-studio/commit/473dd7de41845f961d33f11a3ecbafdfbe62cdb1

You are correct, I needed to have separate program/preview feedbacks to accomplish this.

It will be in a future beta of Companion v3

**Comment by bryce-seifert** [comment]
@nacalai This is now available in the 3.0 beta
