### ISSUE TITLE
Issue with source visibility when in nested scenes.

### ISSUE THREAD

**Issue by thargy** [bitfocus/companion-module-obs-studio#21]
When toggling a source in a nested scene, the filter does not realise that the source is now visible.

I've been trying to find a reliable way to have various overlay options display 'globally', that is over multiple scenes, and toggle various sources on and off.  This allows various lower-thirds to be displayed, whilst switching the main program scenes (e.g. between cameras).

After much-failed experimentation, the closest I've achieved to set all the overlay items in an 'Overlay' scene and to show/hide individual overlays as required.  This has the apparently unique benefit of effecting the Program scene (in Studio media) immediately, without having to re-transition to the scene, as normally occurs when showing a source directly in the current scene.  It also ensures that the visibility continues across actual scene transitions, and, with the hopefully imminent addition of [UI: Add visibility transitions](https://github.com/obsproject/obs-studio/pull/1905), we have a complete solution.

Of course, the feedback doesn't detect the visibility of the sources as they are in a nested scene rather than the visible scene.  For visibility to be accurate therefore, it requires recurring through the scene's sources looking for visible child scenes, that contain the source in a visible state.

**Comment by bryce-seifert** [comment]
@thargy I just did some work on the source visibility feedback, so I can dive back into this and see if I can get nested scenes working.

**Comment by bryce-seifert** [comment]
@thargy So we may be in a bit of a holding pattern. It looks like the path of least resistance to implement this would be to use a "G[etSceneItemList](https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#getsceneitemlist)"  request to see what sources are in a scene and check their visibility. However, that is still listed as unreleased.

So, I have some code ready for when that is released and if it works as expected I can push it.

**Comment by thargy** [comment]
Thanks @bryce-seifert!

**Comment by mu71rd** [comment]
was there any progress on whether it's possible to see visibility within nested scenes? Would be great to be able to see that as Instance Feedback - so it will toggle a chosen 'source: nest scene' on and off visually. 

I am operating the method described by thargy - with all my overlays in a scene, which appears (nested) as sources in my main scenes. As it stands I can't see feedback within Bitfocus as to which overlays are visible and not.

**Comment by eric** [comment]
I've created #38 that handles this scenario without relying on `GetSceneItemList`.
