### ISSUE TITLE
[FEAT REQ] : Support for CallVendorRequest

### ISSUE THREAD

**Issue by jmcc94** [bitfocus/companion-module-obs-studio#220]
While you have a Custom Command action, it would be nice to have a specific one for CallVendorRequest, with the inputs for the correct fields... 

What would be super amazing, would be able to somehow show feedback based on Vendor events. 

I'm mainly looking at how to control the Downstream Keyer plugin using Companion.

**Comment by bryce-seifert** [comment]
I've added the vendor request action with https://github.com/bitfocus/companion-module-obs-studio/pull/223

I'm not entirely sure how to implement the feedback, given how many different plugins there are with varying parameters. I'll think on it a bit, but I'm trying to think of something that can scale and adapt to other plugins

**Comment by jmcc94** [comment]
Awesome! Thanks

I was thinking maybe something like a custom text field in the feedback that was evaluated against the vendorName of the VendorEvent...

Or, if there a way to specify the appropriate vendor plugins in the config screen, and create the appropriate actions, variables & feedbacks from that list?

Just some random thoughts
