### ISSUE TITLE
"Source Visible in Program" feedback seems to have no effect

### ISSUE THREAD

**Issue by phill-85** [bitfocus/companion-module-obs-studio#238]
**Describe the bug**
"Source Visible in Program" feedback seems to have no effect.

![image](https://github.com/bitfocus/companion-module-obs-studio/assets/4619659/e94a84a1-061c-4bca-ac85-819fcd1a41f4)

![image](https://github.com/bitfocus/companion-module-obs-studio/assets/4619659/84427d59-0a84-4af5-b5ea-d33b8a38bf19)

**Version Information:**

- Operating System: Ubuntu 23.04
- OBS Version: 29.1.3
- Companion Version: 3.1.3+6086-beta-a7a34582

**Comment by phill-85** [comment]
The experimental version does not appear to work either.

**Comment by bryce-seifert** [comment]
I have not been able to recreate this.

Would you mind attaching your OBS scene collection file so I can test with that?

**Comment by phill-85** [comment]
I double checked and still have the issue...

[Page.companionconfig.txt](https://github.com/bitfocus/companion-module-obs-studio/files/12352796/Page.companionconfig.txt)
[Scene Collection.txt](https://github.com/bitfocus/companion-module-obs-studio/files/12352798/Scene.Collection.txt)

**Comment by bryce-seifert** [comment]
@phill-85 Finally getting around to testing with your project, and I'm still having issues replicating.

Can you try the latest version of OBS and Companion to make sure?

Here's my test environment with the setup, and it is working for me:
<img width="2560" alt="Screenshot 2023-09-02 at 8 18 25 PM" src="https://github.com/bitfocus/companion-module-obs-studio/assets/50299051/caa6e650-f792-4572-9db8-b3c5fc4b9c16">

**Comment by phill-85** [comment]
I found if i turn 'duplicate sources' off  in obs then "obs: Source Visible in Program" appears to start working as expected, turn it back on and it appears to break again.

![image](https://github.com/bitfocus/companion-module-obs-studio/assets/4619659/cb573339-1c32-481a-922e-70ec6fbd2a10)

**Comment by bryce-seifert** [comment]
Thanks for the additional information, I am able to replicate the issue after toggling Duplicate Sources.

However, I don't think there is a fix that can be implemented in the module, I think it will have to come from OBS or obs-websocket.

When I switch Duplicated Sources to "on" I get this event from obs-websocket
`{ inputName: 'GREEN', videoActive: false }`
and likewise when I switch it "off", I get 
`{ inputName: 'GREEN', videoActive: true }`

So there's nothing that can currently be done within the module to detect this behavior and account for it. My first recommendation would be to find workarounds to using Duplicated Source, or if that is not possible raise an [issue with obs-websocket](https://github.com/obsproject/obs-websocket/issues), as we would need that data to be correct in order for the feedback to work properly.
