### ISSUE TITLE
Option to use variables for selection boxes

### ISSUE THREAD

**Issue by slords** [bitfocus/companion-module-obs-studio#239]
Some functions offer a <CUSTOM SCENE NAME> where you can put a variable in but others don't.  I'm needing functionality that allows me set most of the parameters using variables instead of dropdowns.  Would it be possible to make it so any option could be filled in using a custom variable?

Specifically, I need the following functions to allow variables.

Set Preview Scene (already done)
Set Source Filter Visibility (need both Source and Filter)
Set Source Visibility (need both Scene and Source)
Source Enabled in Scene (need both Scene and Source)

Thanks for your consideration

**Comment by slords** [comment]
The Set Source Filter Visibility I can work around by using a custom call but the other one I cant.

**Comment by bryce-seifert** [comment]
I agree that having variables would be helpful in many cases.

This will likely have to wait until https://github.com/bitfocus/companion/issues/2345, as that would be the most straightforward implementation of this instead of having to add a toggle for every action.

**Comment by MeestorX** [comment]
This is already possible within Companion. My module allows variables in drop-downs for example.

**Comment by bryce-seifert** [comment]
I know it can be added manually to every action, but with the number of actions in the module I think the more straightforward long term solution is to use something like https://github.com/bitfocus/companion/issues/2345 is discussing.

**Comment by MeestorX** [comment]
Not sure I know what you mean.
The only types that you can't use variable on are numbers and booleans. You were speaking of drop downs, no? If you were, then they (and text fields) already support variables.
Maybe you can give an example or explain more what you are looking for?

**Comment by bryce-seifert** [comment]
I understand they support variables. But that would require adding variable parsing for every option, when the simpler implementation would be Companion-wide the ability to make any field an expression.

I'll look at adding variables for the actions listed above regardless so we can close this out.

**Comment by slords** [comment]
Any progress on this?

**Comment by bryce-seifert** [comment]
In the latest Companion beta, you should now be able to type into the dropdown boxes on the requested actions/feedbacks. This will allow you to paste custom variables, and it will parse those when executing. Let me know if you run into any issues

<img width="599" alt="Screenshot 2024-06-02 at 10 01 17 AM" src="https://github.com/bitfocus/companion-module-obs-studio/assets/50299051/1968b558-a623-4e91-9499-640d4a19b13d">

**Comment by slords** [comment]
This appears to be working well except for one thing.  When I use a variable for feedback on a button it isn't being updated when the variable changes.  It will update the feedback if I click on the button but it should update any time the variable value changes.

**Comment by bryce-seifert** [comment]
Got it, I think I know why that is. I will work on a fix.

**Comment by bryce-seifert** [comment]
@slords This should be fixed in the next module version, 3.6.0, which should be in Companion beta builds by tomorrow.
