### ISSUE TITLE
feature request: Set Source Filter Visibility <ALL FILTERS>

### ISSUE THREAD

**Issue by karlthepagan** [bitfocus/companion-module-obs-studio#241]
I would like to have an option to set source filter visibility for all filters on that source.

MOCKUP:
![Screenshot 2023-10-25 at 12 14 54 PM](https://github.com/bitfocus/companion-module-obs-studio/assets/308745/74a5ae5d-12ac-4bb6-986f-d2d2a1fad5db)

I currently greatly appreciate the ability to toggle/mute all sources in a scene. The change to target all of a group of things with such a mutation greatly simplifies my OBS workflows. If that is only possible because of an OBS change please let me know.

**Comment by karlthepagan** [comment]
Here is a similar use-case for SOURCE VISIBILITY, demonstrating why I find this so useful in the current OBS module.
![Screenshot 2023-10-25 at 12 14 54 PM](https://github.com/bitfocus/companion-module-obs-studio/assets/308745/6d9b29dc-b0f0-4e30-804b-71b4556eb59f)

I have tested this and it's over 90% stable, sometimes the "Visibility On" call does not work, but I am satisfied with the behavior enough. I will also accept having to add a delay or wait for the key-up to perform the visibility on action.

**Comment by karlthepagan** [comment]
Here is a similar use-case for SOURCE VISIBILITY, demonstrating why I find this so useful in the current OBS module.
![Screenshot 2023-10-25 at 12 14 18 PM](https://github.com/bitfocus/companion-module-obs-studio/assets/308745/98fa04a3-ac00-4cb0-afe2-843a81f7735e)

I have tested this and it's over 90% stable, sometimes the "Visibility On" call does not work, but I am satisfied with the behavior enough. I will also accept having to add a delay or wait for the key-up to perform the visibility on action.

**Comment by bryce-seifert** [comment]
@karlthepagan I've added this via https://github.com/bitfocus/companion-module-obs-studio/commit/d1069bc4b858d5ffee043b08e3a6ed7b437c4563. I've also hopefully made Source Visibility more reliable, but changing it to a batch request
