### ISSUE TITLE
obs: Set SCENE Filter Visibility

### ISSUE THREAD

**Issue by ahfauth** [bitfocus/companion-module-obs-studio#244]
It would be great to have the option to set scene filter visibility same as we have for source filter visibility.

Some of my scenes have filters I would be great to turn them on/off using Companion.

Thanks!

**Comment by ahfauth** [comment]
Nevermind... It actually works when I select  "obs: Set Source Filter Visibility" and select the scene. Not very intuitive but it works! Sorry about that!

**Comment by bryce-seifert** [comment]
Good point, I should probably rename it to just "obs: Set Filter Visibility" for clarity.

**Comment by ahfauth** [comment]
That would be nice!
