### ISSUE TITLE
Possible to Control desktop Window or Create Macros?

### ISSUE THREAD

**Issue by ahfauth** [bitfocus/companion-module-obs-studio#245]
I would like to know whether is possible to control a window (ex: resize a browser window) using Bitfocus companion.

It would be nice to also be able to move the mouse and control clicks (create macros)

I use linux and KDE plasma  in case someone has any idea for me.

Thanks!

**Comment by bryce-seifert** [comment]
@ahfauth Are you talking about browser windows within OBS, or the actual browser on the computer?
If OBS, you can use the "Set Source Transform" action.

If the computer, the typical answer is [VICREO Listener ](http://www.vicreo-listener.com/downloads/)app, and the VICREO module in Companion. There is a Linux version, but I'm not sure about compatibility.

**Comment by ahfauth** [comment]
VICREO Listener works perfectly! Thanks @bryce-seifert !
