### ISSUE TITLE
Variable `obs:free_disk_space` without text in it?

### ISSUE THREAD

**Issue by chrisspiegl** [bitfocus/companion-module-obs-studio#251]
I was just setting up Companion with OBS Studio and wondered if it would be possible to get a Feedback button for the remaining disk space to turn red once it's less than 10 GB for example.

As it stands, I found the variable `obs:free_disk_space` and that I can use it in the Feedback `Internal Variable Check Boolean Expression` or `Check Value`. However, the `obs:free_disk_space` appears to include the text " GB" at the end instead of a parsed bytes or GB number only.

Would it be possible to parse this, or setup a variable which is pre parsed for things like this type of feedback button?

Warm Regards,
Chris

**Comment by thedist** [comment]
In Expressions you can use the function `substr(value, start, end)` to remove the characters from the start/end of a string. So for eaxmple `substr($(obs:free_disk_space), 0, -3)` would return the variable without ` GB` or ` MB`.

It'd still have issues when going from GB to MB as suddenly it'd jump from a low number to a high number which would throw off feedback, so ideally there should still be a variable with a raw variable, but for the time being this may meet your needs to remove the ` GB` from the end.

**Comment by chrisspiegl** [comment]
Thank you, @thedist, that indeed helps (see screenshot below). And I agree with the end statement: it still would be helpful to have the “clean value”.

I also added some bits to the expression for the Feedback, which makes it possible to work with the MB & GB (though I don't know if it would jump to `TB` for big drives).

This expression should make it so that it is `true` when the disk space is in the `MB` area or when it's `GB` and less than 10 (or whatever number you put there).

I set it up so that the color is yellow with less than `50 GB` left, and then turns red when there is less than `10 GB` left on the internal disk.

```
(
  substr($(obs:free_disk_space), -2) === 'MB'
  || (
    substr($(obs:free_disk_space), -2) === 'GB'
    && substr($(obs:free_disk_space), 0, -3) < 10
  )
)
```

<img width="798" alt="Xnapper-2024-02-06-09 45 34" src="https://github.com/bitfocus/companion-module-obs-studio/assets/1096384/11d3a6f1-2348-43eb-8ac8-1dd9f58cabaa">

**Comment by bryce-seifert** [comment]
@chrisspiegl I have this merged and it will appear in a future version of the module.
The changes made are:

- New "Disk Space Remaining" feedback, where you choose an amount in MB and it will trigger if it goes below that
- New free_disk_space_mb variable, with returns the raw value of MB with no units, in case you still need that for other expression operations

**Comment by bryce-seifert** [comment]
Currently modules are bundled with Companion, so you have to update the whole app. It will appear in beta there first and then in the next release.

I need to finish up a few other changes, but hope to have this in the betas soon, ideally this weekend.

**Comment by bryce-seifert** [comment]
@chrisspiegl This should be in the Companion beta version for you to try now.

**Comment by chrisspiegl** [comment]
@bryce-seifert - I downloaded the latest beta of Companion, and it is in there and working. Great work and I appreciate the fast implementation 👍.

I played around the parameters to see how they reacted, and the setup of the preset with the red and yellow feedback is exactly as I would have set it up as well.

Wonderful.
