### ISSUE TITLE
Congestion Green when not Streaming

### ISSUE THREAD

**Issue by chrisspiegl** [bitfocus/companion-module-obs-studio#262]
I just found that I can have feedback on a button showing the “congestion” of a stream. 

Two improvement ideas:

1. Would it be possible to make the different congestion states/colors part of the configuration?
2. When adding custom colors, I think it would be a good idea to add a color option which should show when the stream is not streaming.

The combination of these two (adding a state for not streaming) and changing the colors based on users' desires would make it possible to set the congestion filter directly on the “Stream On/Off” button and show:

- `green` - when streaming and everything is good
- `orange` - when streaming and slightly congested
- `red` - when streaming and heavy congested
- `grey` or `transparent` - when not streaming at all

Best,
Chris

**Comment by chrisspiegl** [comment]
Wow @bryce-seifert, this has been fast and such a clean implementation on this and the transition in progress variable. Thank you 🌸.

**Comment by bryce-seifert** [comment]
Thank you for the good suggestions! Since the infrastructure was already there for the feedbacks, both were pretty easy to implement and hopefully are helpful! Let me know if you need anything else
