### ISSUE TITLE
Source pull-down list for the Set Source Text action does not show the OBS text sources within a OBS source group.

### ISSUE THREAD

**Issue by CDMalwitz** [bitfocus/companion-module-obs-studio#263]
**Describe the bug**
Source pull-down list for the Set Source Text action does not show OBS text sources within source groups.  This works in previous versions of Companion. 
![Screenshot 2024-06-01 at 10 17 27 AM](https://github.com/bitfocus/companion-module-obs-studio/assets/118911516/7c475695-4b65-49a7-bd6d-298590158572)
![Screenshot 2024-06-01 at 10 18 22 AM](https://github.com/bitfocus/companion-module-obs-studio/assets/118911516/feebc8c9-833b-42e2-9ff9-63b35864fde9)

!!!!  Notice that "Person Title", "Song Name", and "Song Writer" does not show up in pull-down list.

 
**To Reproduce**

1.  Create a scene within OBS and add multiple text sources.
2. Create a source group in the same scene and drag some of the text sources into the group.
3. In Companion add the action OBS: Set Source Text to a button.
4. You will notice in the source pull-down the text sources in the group source are not included in pull-down list.

**Version Information:**

- Operating System:  macOS Sonoma 14.5 (M1 Max)
- OBS Version: 30.1.2 (64 bit)
- Companion Version: 3.3.0

**Comment by bryce-seifert** [comment]
Fixed with https://github.com/bitfocus/companion-module-obs-studio/commit/8e78e68dc9032b48e1ff6d5fa7db71e85d0ad1f5

**Comment by bryce-seifert** [comment]
This should be fixed in the latest Companion 3.4 beta build. Let me know if it is still an issue

**Comment by CDMalwitz** [comment]
Thanks!Sent from my iPadOn Jun 2, 2024, at 10:04 AM, bryce ***@***.***> wrote:﻿
This should be fixed in the latest Companion 3.4 beta build. Let me know if it is still an issue
