### ISSUE TITLE
Companion 2.1 slows down OBS's UI response whereas v2.0 is OK

### ISSUE THREAD

**Issue by SamWdW** [bitfocus/companion-module-obs-studio#27]
I'm using Companion to control OBS, switching between scenes that contain NDI sources and nested scenes. However OBSs becomes *very* sluggish after just a few minutes of switching between scenes. This happens when it's controlled by Companion v2.1, but interestingly it works OK if I uninstall v2.1 and install v.20 instead, all other things remaining unchanged. Without Companion at all it's perfectly slick. Companion is also controlling an X32 mixer and PTXOptics cameras (all OK).

OBS itself doesn't report high CPU usage, nor any dropped frames, in fact the whole PC is only using about 40% CPU max, and 50% RAM max, so it doesn't appear to be a resources issue. 

**However the mouse "hourglasses" over OBS and it takes 5-10 seconds to respond to any UI activity.**
The log files generated by OBS don't appear to give any clues (any guidance would be appreciated please), and they are not lengthy (I wondered whether it was spending time pushing out lots and lots of websockets logs, and although there's quite a bit it doesn't look like an endless loop type of situation).

**Setup:**
17:30:16.026: CPU Name: AMD Ryzen 7 3700X 8-Core Processor             
17:30:16.026: CPU Speed: 3600MHz
17:30:16.026: Physical Cores: 8, Logical Cores: 16
17:30:16.026: Physical Memory: 16333MB Total, 12407MB Free
17:30:16.026: Windows Version: 10.0 Build 18363 (release: 1909; revision: 1082; 64-bit)
17:30:16.026: Running as administrator: true

OBS v26 RC2, running on the same PC as Companion.
Streamdeck plugin uninstalled (although the issue still happened when it was installed)
OBS websockets plugin v4.8
Companion v2.1.0

**What I've tried:**
I've tried removing all use of "Instance feedback" from the Companion configuration, but that didn't clear the problem.
Nothing untoward is shown on the log in the Companion GUI - i.e no long looping lists of activity.

I've tried reinstalling an older version of Companion and found that the problem goes away with v.2.0 and so **this appears to be related to using v2.1 only**.

Does anyone have any suggestions of what I can capture, or where I could find logs which might shed some light on what's happening, please?

**Comment by bryce-seifert** [comment]
Hey Sam, have you tried one of the recent dev builds of 2.1.1? I'm curious if the issues persists. I'd recommend trying companion-2.1.1-feee27f-2599-win64 if you haven't, available on the [builds page](https://bitfocus.io/companion/download/builds/).

I think there was a change related to how active sources are tracked for button feedback between those two releases, so wondering if that has something to do with it. Let me know if 2.1.1 still has the issue and if so I'll try and dive into this more

**Comment by SamWdW** [comment]
Hi Bryce,
Thank you - I've not tried anything newer than 2.1.0 since finding the problem, so I'll give the latest 2.1.1 build a try and report back!

**Comment by SamWdW** [comment]
Hi Bryce - Good news: I've tried the latest 2.1.1 build, 2606, and the problem with OBS does indeed seem to have gone away.
Thank you!
