### ISSUE TITLE
Set Transition Duration with Custom Variables

### ISSUE THREAD

**Issue by DJDGamess** [bitfocus/companion-module-obs-studio#273]
Set Custom_variables as transition duration.

Example: if you have a + and - button you can change the "Custom_Variable".
In the 'Set Transition Duration' action you set 'Transition time (in ms)' to "Custom_variable".
Now you can change the 'Transition time (in ms)' with + and - buttons

**Comment by bryce-seifert** [comment]
Currently Transition Duration field is a "number" type, so it doesn't support variables which are text based.

Would it be sufficient to have a new action that allows you to adjust the duration up and down by set values? Or is it important that you be able to use variables specifically?

**Comment by DJDGamess** [comment]
I think having both is nice. Personally I use variables a lot, but it would be easier to have a action for it.

In the way I have set it up right now I'd probably say variables just because I'am used to it.

**Comment by bryce-seifert** [comment]
This should now be possible in the latest Companion beta. I added a variable option to Set Transition Duration, as well as a separate Adjust Transition duration action that just takes a number
