### ISSUE TITLE
Previous Active Scene

### ISSUE THREAD

**Issue by slords** [bitfocus/companion-module-obs-studio#274]
I don't know if this is possible, but it would be nice to know what the prior active scene was when there is a scene change.  I have the need to have a trigger run when the scene changes from a known scene.  There are ways to work around this but having it available as a variable that can be used to activate a trigger or feedback would be very nice.

**Comment by bryce-seifert** [comment]
This should now be possible via a variable (scene_previous) or feedback (Previous Scene) in the latest companion beta
