### ISSUE TITLE
Support string for Trigger Hotkey by ID

### ISSUE THREAD

**Issue by slords** [bitfocus/companion-module-obs-studio#279]
Now that the 3.4 branch supports Set Filter Visibility using strings for source and filter, the only thing left for me to completely remove custom API calls is the ability to pass a string to the Trigger Hotkey.  I do have a workaround by doing the custom API call but it would be nice to have this as a string or expression.

**Comment by bryce-seifert** [comment]
This is not available in the latest Companion beta

**Comment by slords** [comment]
This works if I pass in a variable name but not if I use an expression.  Would it be possible to make it so I can reference an element of an array with a variable or do some other calculation in order to determine which hotkey to trigger?

**Comment by bryce-seifert** [comment]
Unfortunately expressions are not available for module actions yet (https://github.com/bitfocus/companion/issues/2345). You would need to use the internal: Custom Variable: Set with expression first, and then use the variable
