### ISSUE TITLE
Feedback - Allow Variables in Scene select (Scene in Preview, Scene in Program)

### ISSUE THREAD

**Issue by MYI-Liva** [bitfocus/companion-module-obs-studio#280]
Currently it is possible to select a scene using variables in "Set Preview/Program Scene".

![image](https://github.com/user-attachments/assets/a50710eb-8655-4f44-b28c-7b2cb4704820)

Unfortunately this is not yet possible in the feedback section.

![image](https://github.com/user-attachments/assets/72073f38-390b-4761-9e8a-704240a24691)

I would appreciate if this feature would be added so I can set up a row of "Set to Preview" and "Set to Program" inclusive feedbacks and it adapting the scenes and order automatically without touching companion to fix the feedback scenes.

**Comment by bryce-seifert** [comment]
This feature should be available in the latest companion beta. It's not a separate textbox like the action, but you can copy/paste a variable into the dropdown on the feedback and it will work!

**Comment by MYI-Liva** [comment]
oh wow perfect thank you.  should have checked the beta first

**Comment by bryce-seifert** [comment]
Oh sorry I was a little confusing—it’s in the latest beta because I just added it after seeing your request! Thanks for your request, and let me know if there are any issues
