### ISSUE TITLE
Media Time Remaining Variable still missing?

### ISSUE THREAD

**Issue by The-Poo** [bitfocus/companion-module-obs-studio#291]
Hi!

At bitfocus.io website I read this:

"Media Source Remaining Time (If remaining time of a media source is below a threshold, change the style of the button)"

Does that mean that there is not a varible accessible with the actually time reamining of the media source ?

Like a count down to zero.

That would be great to have. Even better if you could add a an event when it hits zero.

If I missing something pleas tell me, but cannot find it in companion either.

Great job all!

**Comment by bryce-seifert** [comment]
There is a `current_media_time_remaining` which shows you the remaining time of the most recently played media source.

There is also a `media_time_remaining_` variable for each individual media source that will show the countdown.

**Comment by The-Poo** [comment]
Thank you!
