### ISSUE TITLE
[Feature Request] Ability to use variables in Set Filter Settings input.

### ISSUE THREAD

**Issue by FiniteSingularity** [bitfocus/companion-module-obs-studio#292]
**Describe the feature**

Currently, the Set Filter Settings action does not seem to support variables in the json string provided.  It would be great to be able to insert variables in the json string, e.g.:

![Image](https://github.com/user-attachments/assets/1a61b497-e7aa-4f9f-9ce9-b71ffee0403e)

**Comment by bryce-seifert** [comment]
@FiniteSingularity Thanks for the request! This should now be an option https://github.com/bitfocus/companion-module-obs-studio/commit/25e9a5e28a50f9012a1bc65c8720a0e436b1644b in the latest Companion beta. Let me know of any issues.
