### ISSUE TITLE
Feature Request: use custom variables in Set Stream Settings

### ISSUE THREAD

**Issue by Clefeav** [bitfocus/companion-module-obs-studio#295]
I'd like to be able to use custom variables in the change stream settings dialogue boxes (URL, key, login and password) 

I tried to do this, but when I look at the result in obs, it is just display the variable reference not the actual value of the variable.  e.g. I see $(internal:custom_stream_URL) in OBS's server field rather than the rtmp://servername:1935 that the variable is currently set to

**Comment by bryce-seifert** [comment]
@Clefeav Thanks for the request! Variable support https://github.com/bitfocus/companion-module-obs-studio/commit/59e9a95a196d398e751760c5c0a1cb646a83f582 should now be available in the latest Companion beta. Let me know if you run into any issues

**Comment by Clefeav** [comment]
Awesome news !!! Thanks to much
Chris
________________________________
