### ISSUE TITLE
change streaming key

### ISSUE THREAD

**Issue by fbosman** [bitfocus/companion-module-obs-studio#35]
Is it possible to design a button that can change the streaming key in OBS?
We will be using OBS on different channels and we would like to be able to switch channel from Companion .

**Comment by eric** [comment]
It looks like this could either be done by using [`SetCurrentProfile`](https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#setcurrentprofile) to change the current profile or [`SetStreamSettings`](https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#setstreamsettings) to adjust the Stream Key (and other parameters) directly.
