### ISSUE TITLE
Change Stream Start / Stream stop

### ISSUE THREAD

**Issue by SNRSE** [bitfocus/companion-module-obs-studio#37]
Hey, could you please add the possibility to just send a stream start/stream stop? 
at the moment it just toggels

Greetings Snrse

**Comment by mattehalen** [comment]
Should be on its way. I missed this function to and fixed it on a Pull request.
Also updated so record has separate buttons for start and stop as well.

**Comment by eric** [comment]
This was solved in #41

**Comment by rbyerly17** [comment]
I'm sorry if this is the wrong place for this but how to I update my OBS module in Companion to get this added functionality. I really need it for a project I'm working on but can't figure out how to do it. Thank you in advance!
