### ISSUE TITLE
Either add more functionality using OBS websockets or give us Raw Websocket commands. 

### ISSUE THREAD

**Issue by TheOtherLonestar** [bitfocus/companion-module-obs-studio#42]
I'd like the ability to Turn filters on and off, start and stop Outputs such as virtual cam, set source positions, scale, etc. I can do this with raw websocket commands so either open up that functionality or give us a Websockets button command. Thanks!

**Comment by bryce-seifert** [comment]
I've added some of the mentioned features (filters, stop/start outputs), and there is also a [generic web sockets module](https://github.com/bitfocus/companion-module-generic-websocket)under dev for Companion if you need more custom control, so I'm going to close this.

**Comment by morleym** [comment]
Not to necro, but I'm encountering this same thought now in 2022- the idea being to have parity with the Companion GUI experience for adding an action with the vMix API with a "custom command" as shown in screenshot here

![image](https://user-images.githubusercontent.com/31675433/152595139-051be81c-8002-48a6-93af-4e2341fdf82c.png)

![image](https://user-images.githubusercontent.com/31675433/152595196-149d0448-4ce1-4c85-8d10-5007efd7c01f.png)

**Comment by bryce-seifert** [comment]
@morleym I've added a Custom command action is the [latest betas](https://bitfocus.io/companion/download/builds/). Give it a try and let me know what you think.

I will say, we've added a lot of actions lately and if you find yourself using a particular custom actions for OBS a lot feel free to request it be added to the module!
