### ISSUE TITLE
[BUG] choosing a scene doesn't work in "toggle visbility scene item"

### ISSUE THREAD

**Issue by DachsbauTV** [bitfocus/companion-module-obs-studio#47]
As i understand this feature it is supposed to change visibility regardless of which scene is currently active.
This however doesn't work. 

To give context why this is needed: 
We have a scene projector on a background screen in the studio, on which we would like to change the output without having to change the scene we are working with at the moment.

**Comment by eric** [comment]
Can you reconfirm this doesn't work? I've been using it successfully.

Additionally, #56 has made these dropdowns instead of fields that need to be typed in.

**Comment by DachsbauTV** [comment]
It does work like a charm now. Many Thanks
