### ISSUE TITLE
OBS-WEBSOCKET API UPDATE

### ISSUE THREAD

**Issue by fraggle69** [bitfocus/companion-module-obs-studio#48]
The current instance within companion for OBS is great, but I would like control of more features available in the obs-websocket API please.  Specifically I am after the SetCurrentSceneCollection command, as referenced here.  https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#setcurrentscenecollection

I'll ofcourse be happy to test/validate.  

In the meantime, I wondered where I could get some assistance in using a companion generic http command to achieve what I am after.  I am a bit confused as to what should go in the URL and the json body.  I had thought the URL was just the IP address:port and the command in the json body, but clearly that's not the case.  Any assistance much appreciated.

**Comment by gohamstergo** [comment]
@josephdadams is there any status on the Generic Websockets instance? I'm not seeing it in 2.2.0.

**Comment by josephdadams** [comment]
No one has submitted code for a generic websockets module. I created the repo and gave @krzyc access to it, but the invitation was never accepted.

**Comment by gohamstergo** [comment]
for future reference: https://github.com/bitfocus/companion-module-generic-websocket
