### ISSUE TITLE
[Trigger HotKey by ID] How can I find the ID

### ISSUE THREAD

**Issue by Miuwcy** [bitfocus/companion-module-obs-studio#50]
i'm so struggling in this....
Available actions said it can Trigger HotKey by ID.
but I don't know where I can find the HotKey ID.
thanks so much

**Comment by high-solutions** [comment]
I have the same issue, a single key is maybe doable, but how do you trigger an "ctrl-alt-shift-1" combo???

**Comment by gohamstergo** [comment]
https://github.com/bitfocus/companion-module-obs-studio/issues/33
