### ISSUE TITLE
[Feature Request] Toggle Filter on/off

### ISSUE THREAD

**Issue by DachsbauTV** [bitfocus/companion-module-obs-studio#51]
Hi everyone,

Would be nice to have the functionality to toggle filter visibility of scenes and sources.

Websocket should be able to do this as it is already implemented in the official Streamdeck app

**Comment by Rizotochaud** [comment]
+1

Filter Visibility is very useful to control plugin filters that react to their visibility state.
According to obs-websocket protocol.md, it's the command SetSourceFilterVisibility
https://github.com/Palakis/obs-websocket/blob/4.7.0/docs/generated/protocol.md#setsourcefiltervisibility
We need to set Source, Source's filter & then the filter's state to make the command work.

**Comment by gohamstergo** [comment]
adding my support. this would be great

**Comment by sunsetsbrew** [comment]
+1 YES!!  I would love this, source filter visibility control would be amazing.

as @Rizotochaud said, https://github.com/Palakis/obs-websocket/blob/4.7.0/docs/generated/protocol.md#setsourcefiltervisibility is the proper implementation

**Comment by BoStaahle** [comment]
+1 I was just looking for this, been trying to get it to fire with obs-cli via Internal: Run and Vicreo Send Shell Command
without luck (but that is probably my end).

You could even add Feedback options with 
https://github.com/Palakis/obs-websocket/blob/4.7.0/docs/generated/protocol.md#getsourcefilterinfo

Does require websocket version 4.9.0 (on MacOS at least.)

**Comment by jmcc94** [comment]
+1

Would enable us to control the fade in / face out of sources within scenes.

**Comment by bryce-seifert** [comment]
@DachsbauTV @Rizotochaud @BoStaahle @gohamstergo @sunsetsbrew Filter toggling is available in the latest beta builds, please test and let me know if there are issues

**Comment by BoStaahle** [comment]
@bryce-seifert works for me, latest beta Companion, OBS 27.0.0 (MacOS), Chroma Key filter toggle with feedback.

Thank you.

**Comment by DachsbauTV** [comment]
Works like a charm! Even with plugin filters! amazing work @bryce-seifert

**Comment by DachsbauTV** [comment]
oh one thing:

The scene filters are missing @bryce-seifert
any chance you could add those too?

cheers

**Comment by bryce-seifert** [comment]
@DachsbauTV I think the filters from the scene should be there, but someone else pointed out you can only select scenes that are also sources. That should be fixed when #100 is merged
