### ISSUE TITLE
[BUG] Websocket and Companion 2.2.0 use a lot of resources and crash OBS

### ISSUE THREAD

**Issue by DachsbauTV** [bitfocus/companion-module-obs-studio#52]
**Describe the bug**
I've been watching this for quite a while now and tried several builds and the problem is consistent.
Additionally Build 2782 doubled my CPU usage from 7% to 14-15% with peaks of up to 25%

The main issue seems to be the connection with the websocket plugin (4.8.0). With the connection active OBS crashes on several scenarios:
- When being closed
- when live and changing from studio mode back to preview mode
- when changing from a large scene collection to another

All of these crashes don't occur when companion is closed or websocket is turned off

The companion log shows nothing unfortunately, however, sometimes when OBS crashes it shows the attached error.

**Desktop (please complete the following information):**
 - OS: Win10 x64 2004
 - Companion Version 2.2.0. Builds 
 - OBS 26.1.

![Screenshot 2021-01-07 at 11 59 17](https://user-images.githubusercontent.com/70434961/103885154-df58cd00-50df-11eb-92f7-d978eb473d8d.jpg)

**Comment by eric** [comment]
I have run into crashes that were fixed by Palakis/obs-websocket#644.

Also, #44 has had a big impact on doing less reloads.

**Comment by DachsbauTV** [comment]
Tried it just now and it still crashes when closing OBS.

CPU Usage seems to be better now though

**Comment by eric** [comment]
@DachsbauTV you tried the latest nightly build of the OBS websocket plugin?

**Comment by DachsbauTV** [comment]
No but someones working on it https://github.com/Palakis/obs-websocket/issues/645#issuecomment-792605103
:)
I unfortunately dont have the time to test at the moment

**Comment by bryce-seifert** [comment]
Looks like the latest version of [obs-websocket 4.9.1](https://github.com/Palakis/obs-websocket/releases/tag/4.9.1) should have a fix for this.

> Fixed multiple scenarios where OBS could crash during shutdown with obs-websocket installed.

**Comment by DachsbauTV** [comment]
Works great now! Thanks fopr the amazing work

**Comment by tt2468** [comment]
This crash is due to Companion running polling operations while the scene collection is changing. This issue can be mitigated on clients using obs-websocket 5.0.0 by pausing polling between the `SceneCollectionChanging` and `SceneCollectionChanged` events.
