### ISSUE TITLE
Transition duration bug in "Transition preview to program"

### ISSUE THREAD

**Issue by micodeyt** [bitfocus/companion-module-obs-studio#55]
When using the "Transition preview to program" action, a 2ms duration is used whatever the "Transition time (in ms)" parameter value I set.

OBS version : 26.1.1
Companion version : 2.1.2

**Comment by bryce-seifert** [comment]
I'm not able to recreate this. Have you tried one of the latest [Beta Builds](https://bitfocus.io/user/downloads)? What version of OBS Websocket are you using?
