### ISSUE TITLE
Creating an OBS instance

### ISSUE THREAD

**Issue by mcavicchi** [bitfocus/companion-module-obs-studio#60]
I am new to this but I stumped my coworker who has been using Companion for awhile. 
I am setting up OBS Studio in Companion for the first time but I am getting an error. Status flicks back and forth between OK and Connecting and the log says "instance(obs) Connection lost to OBS". 
I was able to setup up OBS in the Stream Deck Software but would prefer to set it up in Companion. 
I was also able to setup ProPresenter successfully in Companion.

Specs:
Macmini M1 2020
Mac OS Big Sur version 11.1
8GB ram
OBS Studio Version 26.1.2 (64 Bit)
Stream deck software version 4.9.3 (13222)
Bitfocus Companion V2.1.2 (2.1.2-f4bcaf3-2679)

Attached is a video of the error log

https://user-images.githubusercontent.com/80657952/111219365-4e561480-85ae-11eb-8904-66c2d11c1552.MOV

Thank you!
Mike Cavicchi
mikecavicchi@gmail.com

**Comment by bryce-seifert** [comment]
I was able to recreate this by setting obs-websocket to "Enable authentication" and then having an **incorrect** password under the config in Companion. It seems to get stuck in a loop of trying to connect.

**Comment by mcavicchi** [comment]
Thank you so much. That was the problem. Fixed!

Mike Cavicchi

**Comment by Ajonymous** [comment]
I am having this same issue currently. OBS Version 27.2.4 (also tried on latest update of OBS). Companion V2.3.1

**Comment by bryce-seifert** [comment]
@Ajonymous To best troubleshoot this issue, please update to OBS 28 and install the Companion beta build from the [Bitfocus site](https://bitfocus.io/companion/download/builds/). Version number should be 2.4.0. Let me know if the issue persists
<img width="782" alt="193180077-2d8f0a8c-d573-45e5-984e-c8d94a5b3214" src="https://user-images.githubusercontent.com/50299051/193932227-df8c1000-bb9e-4d3d-b5b7-b3012c03c5cd.png">

**Comment by Ajonymous** [comment]
Thanks for that. I tried an older version of the OBS websocket plugin and that worked. I needed to keep on OBS version 27 due to other plugins being incompatible with OBS version 28.
