### ISSUE TITLE
Instance Feedback for new Outputs (Virtual Camera)

### ISSUE THREAD

**Issue by timmilne** [bitfocus/companion-module-obs-studio#69]
#66 closes #49 functionality wise, but now we need instance feedback, and a start/stop toggle like Streaming:

Key Down/On Actions:
OBS: Start and Stop Output (with a drop down selector to specify which output)

Instance Feedback
OBS: Output is On (with a drop down selector to specify which output)

**Comment by atscomms** [comment]
I tried thess "obs: Start (Stop) Output, They didn't work. 
I can control sources and scenes, but these actions don't seem change the state of the Virtual Camera

**Comment by timmilne** [comment]
> I tried these "obs: Start (Stop) Output, They didn't work.
> I can control sources and scenes, but these actions don't seem change the state of the Virtual Camera

They work fine for me.  I'm using the following versions OBS/Websockets/Bitfocus on a PC and Mac:

OBS: 26.1.2
OBS Websockets Server plugin: 1620 (or later, I'm using 1654) <-- This is important
Bitfocus Companion (Experimental Build): 3158

https://bitfocus.io/companion/download/build/companion-2.2.0-2ee698e6-3159-mac.dmg
https://bitfocus.io/companion/download/build/companion-2.2.0-2ee698e6-3159-win64.exe
https://bitfocus.io/companion/download/build/companion-2.2.0-2ee698e6-3159-linux.tar.gz
