### ISSUE TITLE
Add support for SetSceneItemProperties

### ISSUE THREAD

**Issue by sytem** [bitfocus/companion-module-obs-studio#7]
https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#getsceneitemproperties

SetSceneItemProperties is command to change parameters for items in specific scene. It can be used for aux function, when there is one scene with NDI output filter, and other scenes as scene source, and then switch visibility of those.

Would probably need to get list of scenes and then sources for those, or then just textfields for names will be also ok.

**Comment by bastiaanrodenburg** [comment]
Added a function to toggle visibilty of scene items. Should be available on next release of Companion 2.0 or when running from the source.
