### ISSUE TITLE
More Variables

### ISSUE THREAD

**Issue by DachsbauTV** [bitfocus/companion-module-obs-studio#72]
Hi amazing people,

I think a couple more variables could go a long way for this module. The most exciting ones I've found are these:

- remaining time and/or state of a playing media source (in combination with the vicreo tally extension one could let the end of a video automatically trigger an action)
- current playing media file name and/or in vlc playlists: next media file name
- Text(GDI+) variable (see the content of a dynamic lower third on a streamdeck button before putting it  on program)

**Comment by DachsbauTV** [comment]
I've found the corresponding info for the Text(GDI+) variable:
- GetTextGDIPlusProperties
- Request field: " `source` | String | Source name"
- Response Item: " `text` | String | Text content to be displayed."

**Comment by bryce-seifert** [comment]
@DachsbauTV The media feedback (plus some media actions) and the text variables should be in the latest beta builds. Please test and let me know if there are any issues!

**Comment by DachsbauTV** [comment]
Thanks @bryce-seifert ! Unfortunately we are currently moving places and i won't be able to test it before mid august... really sorry about that

**Comment by DachsbauTV** [comment]
hey @bryce-seifert 

Thanks for hte great work, everything works fine. Especially the variable for the text source is a game changer for us!

The only thing I'm still missing (though i don't know if possible) would be a variable for the name of the currently playing/visible media file?

**Comment by bryce-seifert** [comment]
@DachsbauTV I need to tinker with that a bit. The main hurdle id that there can be many media clips playing a once within OBS, depending on how your scenes are setup, so trying to think if there's a useful way to display that data.
