### ISSUE TITLE
Issue With Source Visibility "Toggle" on a Source That's in a Group

### ISSUE THREAD

**Issue by MixDatSalt** [bitfocus/companion-module-obs-studio#78]
The issue is that the "Toggle" option only activates the Source if it's in a group. It does not hide it.

Setting the value to "True" or "False" both work perfectly even if "x" source is in a group so this should be possible to fix unless I'm missing something.

Obviously, there are workarounds such as making a hotkey ID for the source or just using True or False and being okay with having to press the button multiple times sometimes for it to change the state. 

Having the toggle function is by far the lightest, cleanest, and most convenient for sure!

**Comment by bryce-seifert** [comment]
I was able to recreate this. This feature also does not seem to function properly when OBS is in Studio Mode. I'll take a look at it.

**Comment by bryce-seifert** [comment]
I found the solution to this. It's going to take a little bit, because it led me to working on a larger re-work of how the module handles grouped sources.

**Comment by MixDatSalt** [comment]
Thanks for looking into it!
