### ISSUE TITLE
Issue with Feedback in Studio Mode for either 'Change Colors when source visible' or 'Change Colour when source enabled in scene'

### ISSUE THREAD

**Issue by jmcc94** [bitfocus/companion-module-obs-studio#79]
The feedback of either 'Change Colors when source visible' or 'Change Color when source enabled in scene' doesn't change when in Studio Mode after successful change.

We have Scene A and Scene B that contain Scene Z as a source, which then itself contains Source 1.

In studio mode, with Scene A in program and Scene B in preview, we then 'Toggle visibility scene item' the Source is toggled appropriately in both preview and program - what doesn't work is the feedback for either 'Change Colors when source visible' or 'Change Color when source enabled in scene' doesn't change state at all - it stays in it's original state.

If not in Studio mode, it all works as expected.

Maybe similar to #78

**Comment by bryce-seifert** [comment]
Yes, I noticed this when I was working on #78. 

My re-write of group handling fixed the issue for sources. I'm still finishing this up, and an item on my to-do is also handling sources in nested scenes
