### ISSUE TITLE
[BUG] Loading a second instance of OBS crashes companion

### ISSUE THREAD

**Issue by champagj** [bitfocus/companion-module-obs-studio#83]
Running companion 2.1.1 on companionPi to a StreamDeck

I have three modules running nicely. ATEM mini, OBS, OSC.

I need to add another instance of the OBS module to control a second PC running another instance of OBS.

**To Reproduce**
On the GUI I lookup and add OBS module
add the IP address for the second PC/OBS
change the server port to match OBS websocket config (I changes port to 4450 to prevent conflict)
click save
I get a "Houston we have a problem" screen and the stream deck in unresponsive
Try to reload page, no response from the IP
 expected to happen.

**Desktop (please complete the following information):**
 - OS: Win10
 - OBS 26.0.2
 - OBS-websocket 4.8.0
 - Companion Version 2.1.1

**Comment by bryce-seifert** [comment]
Have you tried this on the latest [2.2.0 Beta Builds](https://bitfocus.io/companion/download/builds/)?

I'm not able to recreate this there. Possible it was related to this bug that was solved: https://github.com/bitfocus/companion-module-obs-studio/issues/60

**Comment by champagj** [comment]
> Have you tried this on the latest [2.2.0 Beta Builds](https://bitfocus.io/companion/download/builds/)?
> 
> I'm not able to recreate this there. Possible it was related to this bug that was solved: #60

I managed to get around the issue at some point on the same built and it is very possible it was related to password confusion. 

In any case this could be closed.
