### ISSUE TITLE
Additional Actions/Feedback/Variables

### ISSUE THREAD

**Issue by jmcc94** [bitfocus/companion-module-obs-studio#84]
Would it be possible to get the following added to the module. They are all available in the obs-websocket protocol document

Additional Actions
- Set Filter Visibility
- Set Transition Duration
- Set Audio Monitor Type
- Take Source Screenshot
- Refresh Browser Source

Additional Feedback
- Transition Started
- Transition Ended
- Current Transition
- Filter Visibility
- Audio state of Source
- Audio Monitor Type

Additional Variables
- Current Transition
- Recording Timecode
- Recording Filename

**Comment by bryce-seifert** [comment]
I'll take a look at adding some of these soon. I know Filter Visibility has been requested before (https://github.com/bitfocus/companion-module-obs-studio/issues/51)

**Comment by bryce-seifert** [comment]
Have a pull request up for most of this. Still working on the following, which will require a bit more work:
- Audio state of Source
- Audio Monitor Type
- Filters

**Comment by jmcc94** [comment]
Happy to test when able to...

**Comment by jmcc94** [comment]
Have started testing what has been merged with companion master (#87).

So far looks good. 

Would it be possible to also get RecordingPaused as feedback, and added to the variables?

**Comment by bryce-seifert** [comment]
Thanks for testing!

I'll add those additions to my list.

**Comment by jmcc94** [comment]
Also - could we also get the transition time back as feedback. Something similar to this X32 feedback...

![image](https://user-images.githubusercontent.com/81594959/114820071-8b623080-9e12-11eb-8c74-0e745058c953.png)

**Comment by bryce-seifert** [comment]
Latest beta should have:
Recording pause color added to recording feedback
Recording "pause" state added to recording variable
Transition duration variable + feedback

**Comment by jmcc94** [comment]
Fantastic - will test when i have a chance.

**Comment by bryce-seifert** [comment]
@jmcc94 Filter toggling is available in latest betas, feel free to test when you get a chance.

That leaves these on the to-do list:

- Audio state of Source
- Audio Monitor Type

**Comment by gohamstergo** [comment]
i see the listing in the beta, but no builds available. any idea? 
![image](https://user-images.githubusercontent.com/8529475/121248362-f8210680-c868-11eb-888f-51ba40efa2f0.png)

**Comment by bryce-seifert** [comment]
@gohamstergo As long as you pick a build more recent than that one, it should be there.

**Comment by gohamstergo** [comment]
oh ok gotcha. wasnt sure if these were all sepearate updates or aggregates. thanks!

**Comment by gohamstergo** [comment]
@bryce-seifert tried latest beta and working great! would it also be possible to toggle the visibility of Scene Filters?

**Comment by bryce-seifert** [comment]
@gohamstergo Hmmm it should work with scene filters. However, I think right now the dropdown is only exposing scenes that are also sources. I look at adding scenes even if they are not also sources.

> similarly, what about Feedback for active/preview Scene, as opposed to Source?
There is a feedback called "Change colors from active/previewed scene", does that accomplish what you're looking for, or are you expecting a different behavior?

**Comment by gohamstergo** [comment]
@bryce-seifert ya, scenes only show if nested within another scene as a source currently.

and i think youre right about the feedback, may have just missed that one. ill check that when im back at my pc. thanks!
