### ISSUE TITLE
[BUG] Trigger by Hotkey ID will only trigger in one scene

### ISSUE THREAD

**Issue by DachsbauTV** [bitfocus/companion-module-obs-studio#85]
Hey people,

I have found something unfortunate about the new hotkey ID feature:

When triggering through companion it will only trigger the first scene that contains the according element (filter in my case) and not everything that has the ID.

Expected behavior is that it triggers every element in OBS that has the same name.

**Comment by bryce-seifert** [comment]
How are you assigning hot keys to filters? As far as I know OBS's default Hot Key settings don't have an option for filters. 

Also, in my testing (using Show/Hide and Hotkeys) the Hotkeys in OBS are Scene specific. When you use the Hotkeys outside of companion, does it perform the expected behavior?

**Comment by DachsbauTV** [comment]
I am using the "Motion effect" plugin to animate my sources, which works as filters that are added to the scenes. 
These can have hotkeys assigned to them

" the Hotkeys in OBS are Scene specific" That is the issue I am encountering. In my logic the hotkey ID should be source specific and not scene specific.

**Comment by bryce-seifert** [comment]
Thank you for the clarification on what plugin you are using.

I think I understand the issue now, and was able to recreate it. I think getting the result you expect would require using [TriggerHotkeyBySequence](https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#triggerhotkeybysequence) instead.

Going to test implementing this to see if it works now.

**Comment by bryce-seifert** [comment]
Just confirmed via testing this is what is needed. Going to work on implementing this soon.

**Comment by bryce-seifert** [comment]
@DachsbauTV Will you give the latest [beta build](https://bitfocus.io/companion/download/builds/) a try and see if the " Trigger hotkey by key" action works for you?

**Comment by DachsbauTV** [comment]
Works perfectly fine :) great work.

Just one little suggestion: change the dropdown field for a regular text field. As companion unfortunately doesn't allows key inputs in Dropdown fields, it can get annoying to scroll through so many letters

**Comment by bryce-seifert** [comment]
@DachsbauTV the dropdown field should take text input and be searchable in this case, is that not working for you? 

This ensures that the exact hotkey ID is correct instead of the user trying to find it on their own.

**Comment by DachsbauTV** [comment]
Sorry my bad, it actually does, it just didn't work at first through my vnc.
 
Thanks @bryce-seifert
