### ISSUE TITLE
Preview to Program Command not Working

### ISSUE THREAD

**Issue by tysnyder12** [bitfocus/companion-module-obs-studio#9]
**Make sure you're on the latest bleeding edge build** (remove this section from the bug report)
*Before you report a bug, make sure you're not reporting something that have been fixed in the master branch by downloading a "latest" build from https://builds.bitfocus.io/companion/*

**Describe the bug**
One instance I am using is OBS connected to the Stream Deck XL via Companion and the bug I am running into is the OBS: Transition preview to program action. Every other action that I have set with OBS works fantastic but every time I use that action it crashes OBS completely.

**To Reproduce**
1. Go to Edit Button
2. Click on Add Keydown/on action
3. Scroll down to OBS: Transition preview to program
4. Set the action to a button
4. See OBS crash when you use the action

**Expected behavior**
This action should transition my scene that is in preview into my program window.

**Desktop (please complete the following information):**
 - OS: Windows 64bit
 - Browser: Chrome
 - Version [10]

**Comment by tysnyder12** [comment]
OBS is on the same computer, and the version is 24.0.3

**Comment by DeeJayMX** [comment]
Same here.
Using Cut transition or Fade transition,
I see the next transition is selected good but don't do the action and it crash 2 seconds after that.

here is the log of the crashed thread:
`Unhandled exception: c0000005
Date/Time: 2019-11-23, 18:45:50
Fault address: 7FF8D73F1E10 (c:\program files\obs-studio\bin\64bit\qt5widgets.dll)
libobs version: 24.0.3 (64-bit)
Windows version: 10.0 build 17134 (revision: 1069; 64-bit)
CPU: Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz


Thread 273C (Crashed)
Stack            EIP              Arg0             Arg1             Arg2             Arg3             Address
000000B6436FF578 00007FF8D73F1E10 00007FF8D7163378 00007FF8D7163378 FFFFFFFFFFFFFFFE FFFFFFFFFFFFFFFF qt5widgets.dll!0x7ff8d73f1e10
000000B6436FF580 00007FF8D71D8859 00000235FE9D78F0 000000B6436FF5F8 00007FF8D7163378 00000235F6836B40 obs-websocket.dll!Utils::TransitionToProgram+0x39
000000B6436FF5B0 00007FF8D71D0991 00007FF8D7163378 000002358B9F5450 000000B6436FF649 00000235FDF5C0D0 obs-websocket.dll!WSRequestHandler::HandleTransitionToProgram+0x161
000000B6436FF5F0 00007FF8D71C44C5 0000000000000000 00000235FDF52200 00000235F6836B40 00007FF8D5336EDA obs-websocket.dll!WSRequestHandler::processRequest+0x2b5
000000B6436FF6B0 00007FF8D71C40A9 000002358B9F5350 000000B6436FF7B0 000000B6436FF7B9 00000235FDF5C0B0 obs-websocket.dll!WSRequestHandler::processIncomingMessage+0xa9
000000B6436FF730 00007FF8D718A7D3 0000000000000000 00000235FDF5C0B0 000002358BD402E0 00000235FDF5C0C0 obs-websocket.dll!<lambda_773ed4aac26f3e00c25c0fcee6d65cf3>::operator()+0xc3
000000B6436FF820 00007FF8D71B9F57 00000235FDF5C0C0 00000235FDF5C0B0 000002358BD402E0 000002358BD402E0 obs-websocket.dll!QtConcurrent::RunFunctionTask<void>::run+0x37
000000B6436FF880 00007FF8D53342F7 000002358BD402E0 00000235F6813C20 000002358BD402E0 00000235F6A81A70 qt5core.dll!0x7ff8d53342f7
000000B6436FF910 00007FF8D53381A7 0000000000000000 0000000000000000 0000000000000000 0000000000000000 qt5core.dll!0x7ff8d53381a7
000000B6436FF950 00007FF9130B4034 0000000000000000 0000000000000000 0000000000000000 0000000000000000 kernel32.dll!0x7ff9130b4034
000000B6436FF980 00007FF913D23691 0000000000000000 0000000000000000 0000000000000000 0000000000000000 ntdll.dll!0x7ff913d23691`

**Comment by Azenet** [comment]
This is a known OBS bug, I have been recommended to use [this early build](https://ci.appveyor.com/project/Palakis/obs-websocket/builds/26020497/artifacts), which worked. I am not sure about the status of this issue on the latest OBS version.
