### ISSUE TITLE
Hotkey ID

### ISSUE THREAD

**Issue by JonaChurch** [bitfocus/companion-module-obs-studio#94]
Hello,
I am not sure it would be the thing for you to give me this  very basic advice,
But this is my question:
I got companion running on OBS and want to use the Trigger Hotkey by ID function
I do not understand everything on the Bitfocus website
They say I need to enter the value of the Hotkey, but I don't know what I have exactly to enter.
This is an example
lyric_clear_hotkey={\n "bindings": [\n {\n "alt": true,\n "key": "OBS_KEY_U"\n }\n ]\n}

So what exactly do I have to enter in the companion menu 
OBS_KEY_U is not enough. 
I would really appreciate your effort answering this simple question. Thank you best regards

Carolina

**Comment by bryce-seifert** [comment]
Here's the text from under the help info under the module, hopefully this example is helpful:
> This file should have a section labeled [Hotkeys]. Under that section, the left most text up until the equals sign is the Hotkey ID. For example, **a Hotkey ID might look like: OBSBasic.StartRecording**

If Hotkey IDs are giving you issues, I would also recommend trying "Trigger hotkey by key" in the [latest betas](https://bitfocus.io/companion/download/builds/), it's slightly simpler to use.

**Comment by JonaChurch** [comment]
thank you for you effort
Please consider I  am not familiar with working on this level of computer languag (its like Chinese language to me), so if someone says „take the value and put it into companion“ I do not know which characters are value, which are not.

I think I just need one example to see then I am good to go

So this is the Hotkey in OBS

SHIFT SPACE


This is the line in the basic.ini

OBSBasic.TogglePreviewProgram={\n    "bindings": [\n        {\n            "key": "OBS_KEY_SPACE",\n            "shift": true\n        }\n    ]\n}

What exactly is going into companion, which characters?   OBS_KEY_SPACE is incomplete. 

Sorry for bothering you
Thank you very much
Carolina


The new Trigger hotkey by key is very nice! Very comfortable! I just tried it.

Is the latest beta reliable enough to work with?

**Comment by bryce-seifert** [comment]
No worries, I'm here to help.

So in that example, what you would enter into companion is:

`OBSBasic.TogglePreviewProgram`

Let me know if that works!

Glad you are liking the Trigger by key feature. I would recommend testing the betas for a while before using them.

**Comment by JonaChurch** [comment]
great, got it. Thank you so much!!

I thought I had to find some necessary stuff from the other characters to put into companion like some of shift and true and so, didn’t know it would be so easy

So I can now go back to the „old“ stable release and do all my hotkey buttons

Thank you!!
Carolina
