### ISSUE TITLE
Action: Toggle visibility scene item, Toggle mode does not disable item which is nested in a group (OBS 27.0.0)

### ISSUE THREAD

**Issue by karlthepagan** [bitfocus/companion-module-obs-studio#97]
OBS 27.0.0

I'm using the "Toggle" mode for item visibility. This works to show, but not to hide the scene items which are nested within groups.

**Comment by karlthepagan** [comment]
![image](https://user-images.githubusercontent.com/308745/120405122-b5a57a00-c2fc-11eb-8861-cc4724bb2168.png)

**Comment by karlthepagan** [comment]
Moving these sources out of their source groups did not resolve the issue.

**Comment by bryce-seifert** [comment]
@karlthepagan Which version of companion are you using? Can you try the a [recent beta build](https://bitfocus.io/companion/download/builds/)?

**Comment by karlthepagan** [comment]
Resolved in companion-2.2.0-12980584-3400-win64.exe
