### ISSUE TITLE
Instance feedback: Change colors when source enabled in scene is not responsive when the source is in a group (OBS 27.0.0)

### ISSUE THREAD

**Issue by karlthepagan** [bitfocus/companion-module-obs-studio#98]
This seems to accept the state when the feedback is created, but it does not update when that source is inside a group.
![image](https://user-images.githubusercontent.com/308745/120405335-2d73a480-c2fd-11eb-8313-3fd1fd6047d7.png)
![image](https://user-images.githubusercontent.com/308745/120405355-36fd0c80-c2fd-11eb-894e-f568161d6f42.png)

**Comment by karlthepagan** [comment]
![image](https://user-images.githubusercontent.com/308745/120405380-48461900-c2fd-11eb-8254-40c89b928222.png)

**Comment by bryce-seifert** [comment]
@karlthepagan Which version of companion are you using?

**Comment by karlthepagan** [comment]
I'm on v2.1.3 / windows

**Comment by karlthepagan** [comment]
Resolved in companion-2.2.0-12980584-3400-win64.exe
